Add - SDB and GPS tracking
acemod/ACE3 pull request #10037
Opened 2024-05-28 03:24 UTC by TheCandianVendingMachine

**When merged this pull request will:**
- GBU-39
- Add a basic GPS tracking seeker, with a JDAM attack profile for angled attacks
## Merge Strategy

Follow #10019 
### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-05-28 14:46 UTC, rautamiekka requested changes

2024-05-28 19:46 UTC, veteran29 commented on addons/missileguidance/functions/fnc_gps_getAttackData.sqf
> +]
What you're suggesting is a deep copy while original code basically does a shallow one, shallow copy would be `[] + GVAR(gps_currentSettings)`. Does not seem to matter in this case.

2025-02-12 05:31 UTC, PabstMirror approved these changes

2025-02-14 21:06 UTC, TheCandianVendingMachine commented on addons/missile_sdb/README.md
> +- [Dani-TCVM](https://github.com/TheCandianVendingMachine)
```suggestion
```

2025-02-14 21:06 UTC, TheCandianVendingMachine commented on addons/missile_sdb/config.cpp
> +        authors[] = {"Dani (TCVM)"};
```suggestion
        authors[] = {"tcvm"};
```

2025-02-16 20:54 UTC, PabstMirror approved these changes

2025-02-17 18:32 UTC, merged