Dogtags - Rename inventory items via CBA
acemod/ACE3 pull request #10130
Opened 2024-07-20 03:19 UTC by PabstMirror

alt to https://github.com/acemod/ACE3/pull/10102
soft-requires https://github.com/CBATeam/CBA_A3/pull/1329

2024-07-20 06:56 UTC, johnb432 requested changes
Overall much more elegant than #10102, hopefully we can get that CBA function merged in 3.18.0.

Would we want to keep the `if (isNil "CBA_fnc_renameInventoryItem") exitWith {};` line if it's merged into CBA?

2024-07-20 06:56 UTC, johnb432 commented on addons/dogtags/XEH_postInit.sqf
> +        private _name = [LLSTRING(itemName), ": ", _dogtagData param [0, LELSTRING(common,unknown)]] joinString "";
The code below is in line with the current code on master (I changed it in #10096)
```suggestion
        private _name = _dogtagData param [0, ""];

        // If data doesn't exist or body has no name, set name as "unknown"
        if (_name == "") then {
            _name = LELSTRING(common,unknown);
        };
        
        _name = [LLSTRING(itemName), ": ", _name] joinString "";
```

2024-07-21 19:23 UTC, PabstMirror commented
I guess `[] call nil` is safe, so it doesn't need to be there, 
I just think it makes it clear why the feature might not work if not running on a dev build of cba, 
we can cleanup when cba3.18 is out

2024-07-23 14:54 UTC, johnb432 approved these changes

2024-07-28 16:43 UTC, merged