Compat - Reaction Forces - Field Rations - Watersource Offsets
acemod/ACE3 pull request #10282
Opened 2024-09-01 18:05 UTC by OverlordZorn

Adds config properties for reaction forces vehicles which can carry drinking water.

2024-09-01 18:10 UTC, OverlordZorn commented
![107410_20240901195108_1](https://github.com/user-attachments/assets/651ee60d-d3cc-4830-9337-9d6ed4730659)
For the Typhoon Water Carrier, i have an optional alternative which is a hatch on the right side, as this would make more sense instead of just in the rear, but:

- this hatch might be for the fuel tank of the vehicle.
- having the accesspoint rear-center might be more intuitive for a normal user.

2024-09-01 18:30 UTC, rautamiekka requested changes
Switching over to ACEX macros. I think I got it right.

2024-09-01 18:30 UTC, rautamiekka commented on addons/compat_rf/CfgVehicles.hpp
> +        acex_field_rations_offset[] = {-0.04, -2.45, -0.9};
```suggestion
        XGVAR(offset)[] = {-0.04, -2.45, -0.9};
```

2024-09-01 18:30 UTC, rautamiekka commented on addons/compat_rf/CfgVehicles.hpp
> +        acex_field_rations_waterSupply = 500;
```suggestion
        XGVAR(waterSupply) = 500;
```

2024-09-01 18:30 UTC, rautamiekka commented on addons/compat_rf/CfgVehicles.hpp
> +        //acex_field_rations_offset[] = {1.25,-1.59,-0.58}; // Right Side Latch
```suggestion
        XGVAR(waterSupply) = 10000;
        XGVAR(offset)[] = {0, -5.05, -0.3}; // Rear
        //XGVAR(offset)[] = {1.25,-1.59,-0.58}; // Right Side Latch
```

2024-09-01 18:30 UTC, rautamiekka commented on addons/compat_rf/CfgVehicles.hpp
> +        acex_field_rations_offset[] = {-0.41,-5.15,-0.3};
```suggestion
        XGVAR(waterSupply) = 10000;
        XGVAR(offset)[] = {-0.41,-5.15,-0.3};
```

2024-09-01 18:33 UTC, OverlordZorn commented
> Switching over to ACEX macros. I think I got it right.
If this would be inside the ACEX Field_Rations Addon itself, it would work. but its inside the compat_rf addon.
The macro would resolve to `acex_compat_rf_offset`, so this would not work.

2024-09-01 18:35 UTC, OverlordZorn commented
you would need to use  `EXGVAR(var1,var2)` as in `EXGVAR(field_ration,offset)`

2024-09-03 02:32 UTC, PabstMirror commented on addons/compat_rf/CfgVehicles.hpp
> +    {
```suggestion
    class Pickup_01_base_rf : Offroad_01_unarmed_base_F {
```

2024-09-03 02:33 UTC, PabstMirror commented on addons/compat_rf/CfgVehicles.hpp
> +    {
```suggestion
    class C_IDAP_Pickup_water_rf: C_IDAP_Pickup_rf {
```

2024-09-03 02:33 UTC, PabstMirror commented on addons/compat_rf/CfgVehicles.hpp
> +    {
```suggestion
    class C_Truck_03_water_rf: O_Truck_03_fuel_F {
```

2024-09-03 02:33 UTC, PabstMirror commented on addons/compat_rf/CfgVehicles.hpp
> +    {
```suggestion
    class C_Truck_01_water_rf : B_Truck_01_fuel_F {
```

2024-09-06 19:41 UTC, Mike-MF commented on addons/compat_rf/CfgVehicles.hpp
> +        //EXGVAR(field_rations,offset)[] = {1.25,-1.59,-0.58}; // Right Side Latch
```suggestion
        EXGVAR(field_rations,offset)[] = {0, -5.05, -0.3};
```

The right side latch is more than likely the fuel tank.

2024-09-06 19:42 UTC, Mike-MF commented on addons/compat_rf/CfgVehicles.hpp
> +        EXGVAR(field_rations,offset)[] = {-0.41,-5.15,-0.3};
```suggestion
        EXGVAR(field_rations,offset)[] = {-0.41, -5.15, -0.3};
```

2024-09-06 20:09 UTC, Mike-MF approved these changes

2024-09-08 07:32 UTC, johnb432 commented on addons/compat_rf/CfgVehicles.hpp
> +    class Pickup_01_base_rf : Offroad_01_unarmed_base_F {
```suggestion
    class Pickup_01_base_rf: Offroad_01_unarmed_base_F {
```

2024-09-08 07:32 UTC, johnb432 commented on addons/compat_rf/CfgVehicles.hpp
> +    class C_Truck_01_water_rf : B_Truck_01_fuel_F {
```suggestion
    class C_Truck_01_water_rf: B_Truck_01_fuel_F {
```

2024-09-08 07:32 UTC, johnb432 commented on addons/compat_rf/CfgVehicles.hpp
> +    // applies the offset to all RF Offroads which can have the optional Tank in the back
```suggestion
    // Applies the offset to all RF Offroads which can have the optional tank in the back
```

2024-09-08 20:50 UTC, PabstMirror approved these changes

2024-09-08 23:07 UTC, merged