missile_hud - Move HUD feature from `laser` to new component
acemod/ACE3 pull request #10306
Opened 2024-09-10 07:50 UTC by TheCandianVendingMachine

**When merged this pull request will:**
- Move HUD functionality from `laser` to `missile_hud`
- Add API to add new HUD elements depending on conditions

the HUD for laser guided munitions lived in `laser` forever. This doesn't make any sense, as the HUD is meant to showcase missile information. A new API was made to be able to extend what is shown to the user, as well as move functionality from `laser`

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-11-22 23:18 UTC, PabstMirror approved these changes

2024-11-23 00:42 UTC, rautamiekka requested changes

2024-11-23 00:42 UTC, rautamiekka commented on addons/missile_hud/XEH_postInit.sqf
> +                [ace_player] call FUNC(showVehicleHud);
```suggestion
            if (isNull _seatAI) then {
                [ace_player] call FUNC(showVehicleHud);
            } else {
                [_seatAI] call FUNC(showVehicleHud);
```

2024-11-23 00:42 UTC, rautamiekka commented on addons/missile_hud/functions/fnc_isElementValid.sqf
> +private _success = if (_type != "SPACER") then {
```suggestion
private _success = if (_type isNotEqualTo "SPACER") then {
```

2024-11-27 01:21 UTC, merged