Medical - Add setting to use limb damage for sum of trauma
acemod/ACE3 pull request #10362
Opened 2024-10-05 13:51 UTC by LinkIsGrim

**When merged this pull request will:**
- Title.
- Cleanup unused vars in handleIncapacitation.

Implementation is a bit lazy:
* You can't set limb DT per-unit (would be neat?)

Damage threshold is per-limb because configuring this as a user is a nightmare otherwise. Default is pretty generous to compensate for lack of armor in the limbs of most units.

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-10-10 20:07 UTC, smitt14ua commented on addons/medical_damage/stringtable.xml
> +            <English>Controls whether limb damage is taken into account for fatality and unconsciousness calculations.</English>
```suggestion
            <English>Controls whether limb damage is taken into account for fatality and unconsciousness calculations.</English>
            <Russian>Определяет, учитывается ли повреждение конечностей при расчете смертности и потери сознания.</Russian>
```

2024-10-10 20:11 UTC, smitt14ua commented on addons/medical_damage/stringtable.xml
> +            <English>Sets the amount of damage a limb can receive before going critical (leading to unconsciousness, or death if "Sum of Trauma" is enabled).\nDoes nothing if the "Use Limb Damage" se
```suggestion
            <English>Sets the amount of damage a limb can receive before going critical (leading to unconsciousness, or death if "Sum of Trauma" is enabled).\nDoes nothing if the "Use Limb Damage" setting is disabled.</English>
            <Russian>Устанавливает величину урона, который может получить конечность прежде, чем он станет критическим (приводит к потере сознания или смерти, если включена "Сумма травм").\nНичего не делает, если настройка "Использовать урон конечностям" отключена.</Russian>
```

2024-10-12 12:04 UTC, smitt14ua commented
Looks like very useful PR for me. Sum of trauma is the most general reason of deaths and we have many complains about it

2024-10-19 10:11 UTC, johnb432 commented on addons/medical_damage/initSettings.inc.sqf
> +    true
```suggestion
    1
```

2024-10-19 10:11 UTC, johnb432 commented on addons/medical_damage/initSettings.inc.sqf
> +    true
```suggestion
    1
```

2024-10-19 10:13 UTC, johnb432 approved these changes
LGTM other than comments

2024-11-03 01:51 UTC, smitt14ua requested changes
Updated Russian translations

2024-11-03 01:51 UTC, smitt14ua commented on addons/medical_damage/stringtable.xml
> +            <Russian>Определяет, учитывается ли повреждение конечностей при расчете смертности и потери сознания.</Russian>
```suggestion
            <Russian>Определяет, учитывается ли повреждение конечностей при расчете совокупности травм.</Russian>
```

2024-11-03 01:51 UTC, smitt14ua commented on addons/medical_damage/stringtable.xml
> +            <Russian>Устанавливает величину урона, который может получить конечность, прежде чем он станет критическим (приводит к потере сознания или смерти, если включена "Сумма травм").\nНичего не
```suggestion
            <Russian>Устанавливает величину урона, который могут получить конечности, прежде чем урон станет критическим, что приведет к смерти. Для любого эффекта должно быть больше 0.\nТребуется, чтобы настройка "Использовать урон конечностям" была включена, а "Причина смертельного урона" была установлена на "Совокупность травмы" или "Оба".\nУмножается с общим порогом повреждения. Никак не взаимодействует с переломами или хроманием.</Russian>
```

2024-11-03 01:58 UTC, merged

2024-11-13 00:09 UTC, BrettMayson commented on addons/medical_gui/functions/fnc_updateBodyImage.sqf
> +                if (!EGVAR(medical,useLimbDamage) || EGVAR(medical,limbDamageThreshold) == 0) then { // Just indicate how close to the limping threshold we are
This will throw an error if the setting is set to `2`