Medical Treatment- IV bag fixes
acemod/ACE3 pull request #10407
Opened 2024-10-13 12:36 UTC by Cplhardcore

**When merged this pull request will:**
- adds a small line to ivBagLocal to give the fluid bag back to the medic rather then poofing
-

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-10-13 14:38 UTC, Cplhardcore commented on addons/medical_treatment/functions/fnc_ivBag.sqf
> +[QGVAR(ivBagLocal), [_medic, _patient, _bodyPart, _classname], _patient] call CBA_fnc_targetEvent;
Fixed

2024-10-13 15:34 UTC, johnb432 approved these changes

2024-10-13 17:35 UTC, PabstMirror requested changes
need to add medic to https://github.com/acemod/ACE3/blob/master/addons/medical_ai/functions/fnc_healingLogic.sqf#L265

2024-10-13 18:09 UTC, PabstMirror approved these changes

2024-10-15 16:17 UTC, merged

2024-12-17 11:55 UTC, johnb432 commented
This is broken, code is trying to add treatment as an item.