Medical Vitals - Extract update logic to separate functions
acemod/ACE3 pull request #10566
Opened 2024-12-17 22:05 UTC by LinkIsGrim

**When merged this pull request will:**
- Makes more sense IMO. Intent is for events to be used as API (IV medication/incompatible blood transfusions, for example).

Event deferral is just to keep any code from the events out of the vitals counter, but they can just be raised straight with no problems.

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-12-17 23:45 UTC, PabstMirror commented on addons/medical_vitals/functions/fnc_consumeMedications.sqf
> +        _adjustments deleteAt _forEachIndex;
help[L-S13]: Undefined Var - _woundBloodLoss
   ┌─ addons/medical_vitals/functions/fnc_updateState.sqf:87:11
   │
87 │     case (_woundBloodLoss > 0): {
   │           ^^^^^^^^^^^^^^^


help[L-S13]: Undefined Var - _woundBloodLoss
   ┌─ addons/medical_vitals/functions/fnc_updateState.sqf:84:11
   │
84 │     case (_woundBloodLoss > BLOOD_LOSS_KNOCK_OUT_THRESHOLD): {
   │           ^^^^^^^^^^^^^^^


help[L-S13]: Undefined Var - _adjustments
   ┌─ addons/medical_vitals/functions/fnc_consumeMedications.sqf:39:9
   │
39 │         _adjustments deleteAt _forEachIndex;
   │         ^^^^^^^^^^^^

2024-12-19 21:39 UTC, rautamiekka requested changes

2024-12-19 21:39 UTC, rautamiekka commented on addons/medical_vitals/functions/fnc_updatePain.sqf
> +// Handle pain due tourniquets, that have been applied more than 120 s ago
```suggestion
// Handle pain due to tourniquets, that have been applied more than 120 s ago
```

2025-01-05 08:10 UTC, johnb432 commented on addons/medical_vitals/functions/fnc_consumeIVs.sqf
> +(GVAR(deferredEvents) getOrDefault [_unit, [], true]) pushBack ([QEGVAR(medical,consumedIVs), [_unit, _consumedIVs]]);
Key can't be an object, you need to use `hashValue` first.

2025-01-05 08:17 UTC, johnb432 commented on addons/medical_vitals/functions/fnc_consumeIVs.sqf
> +(GVAR(deferredEvents) getOrDefault [_unit, [], true]) pushBack ([QEGVAR(medical,consumedIVs), [_unit, _consumedIVs]]);
Generally not a huge fan of having a global hashmap for this kind of thing:
1) If the unit is deleted, you need to handle the removal from the hashmap.
2) If the unit switches locality, this can't handle it. Idk how important that is though.

Why not use an object variable instead? Handles 1) and no longer requires `hashValue _unit`.

2025-01-05 13:29 UTC, johnb432 commented on addons/medical_vitals/functions/fnc_consumeIVs.sqf
> +(GVAR(deferredEvents) getOrDefault [_unit, [], true]) pushBack ([QEGVAR(medical,consumedIVs), [_unit, _consumedIVs]]);
> I'd rather just raise the events outright

Do that then, makes more sense.

2025-02-01 00:05 UTC, PabstMirror commented on addons/medical_status/functions/fnc_updateWoundBloodLoss.sqf
> +            _partBleeding = _partBleeding + (_amountOf * _bleeding);
```suggestion
            _partBleeding = _partBleeding + (_amountOf * _bleeeding);
```

2025-02-01 00:06 UTC, PabstMirror commented on addons/medical_vitals/functions/fnc_updatePain.sqf
> +private _oldestTourniquetTime = selectMin _tourniquets;
I think
```suggestion
private _oldestTourniquetTime = selectMin _activeTourniquets ;
```

2025-02-08 10:59 UTC, johnb432 commented on addons/medical_vitals/functions/fnc_updateHeartRate.sqf
> + * None
Either you need to revert this
```suggestion
 * Current Heart Rate <NUMBER>
```
or you need to remove the return value.

2025-02-08 10:59 UTC, johnb432 commented on addons/medical_vitals/functions/fnc_updatePain.sqf
> +private _oldestTourniquetTime = selectMin _activeTourniquets ;
```suggestion
private _oldestTourniquetTime = selectMin _activeTourniquets;
```

2025-02-08 10:59 UTC, johnb432 commented on addons/medical_vitals/functions/fnc_consumeMedications.sqf
> +    [0, 0, 0, false]
```suggestion
    false // return
```

2025-02-08 22:01 UTC, johnb432 approved these changes

2025-02-08 22:33 UTC, merged