Arsenal - Provide reference to the current box
acemod/ACE3 pull request #7948
Opened 2020-10-07 01:46 UTC by BrettMayson

**When merged this pull request will:**
- Provider a reference to the current box

Useful for mods that modify the arsenal

2020-10-07 04:29 UTC, bux commented
why `box`?

2020-10-07 04:37 UTC, BrettMayson commented
The related functions are `initBox`, `openBox`, and `removeBox`

2020-10-07 04:50 UTC, bux commented
Yeah, I know, pretty unlucky choice of names ... shame on you alganthe 😄 

Imho, I'd prefer something like `currentArsenalObject` or similar.

2020-10-07 07:30 UTC, BrettMayson commented
If it were a new feature, yeah, I'd agree. I do think it is better however to stay consistent with the existing public functions.

2020-10-08 02:39 UTC, mharis001 commented on addons/arsenal/functions/fnc_openBox.sqf
> +GVAR(currentBox) = _object;
Should move below L44 since function might exit without creating display and then `onArsenalClose` won't run to reset the variable to `objNull`.

2020-10-21 15:45 UTC, PabstMirror requested changes
see above

2020-10-25 15:52 UTC, PabstMirror approved these changes

2020-10-26 17:00 UTC, veteran29 approved these changes

2020-10-26 17:01 UTC, merged