Active Radar Homing: Use AGL for `nearestObjects` check
acemod/ACE3 pull request #8045
Opened 2020-12-13 22:42 UTC by TheCandianVendingMachine

**When merged this pull request will:**
- Fix bug where AGM-114L used `positionASL` instead of `positionAGL` to check for targets

When developing I always used Altis near sea level for moving targets. This caused me to not catch this. Whoops

2020-12-13 23:02 UTC, jonpas requested changes

2020-12-13 23:02 UTC, jonpas commented on addons/missileguidance/functions/fnc_seekerType_ARH.sqf
> +
```suggestion

```

2020-12-13 23:05 UTC, jonpas commented
I meant the spaces on the empty line. Empty line itself is fine. :D

2020-12-13 23:05 UTC, jonpas approved these changes

2020-12-14 06:25 UTC, PabstMirror approved these changes

2020-12-16 03:01 UTC, merged