markers - Add scale slider
acemod/ACE3 pull request #8059
Opened 2021-01-06 17:00 UTC by frankplow

When merged this pull request will:
- Add scale slider to marker placement dialog
- Update map EHs to reflect current selected scale
- Update marker placement scripts to incorporate scale

Apologies for the duplicate PR. I forgot to create a [frankplow:resizable-markers](https://github.com/frankplow/ACE3/tree/resizable-markers) branch initially, and thought I could move the commits over then edit the PR to the new branch but instead github auto-closed the PR as it saw no new commits.
Conflicts from the PR in #8034 are resolved.

2021-02-27 04:29 UTC, PabstMirror commented
Fixed merge conflicts from 8034
lgtm
![image](https://user-images.githubusercontent.com/9376747/109375386-f61ad500-7881-11eb-9fb3-c64cb8fb401a.png)

only minor issue is text can get a bit far from big markers, but that's not something we can fix

2021-04-20 10:31 UTC, jonpas requested changes

2021-04-20 10:31 UTC, jonpas commented on addons/markers/functions/fnc_onSliderPosChangedScale.sqf
> + * [Slider, 1.5] call ace_markers_fnc_onSliderPosChangedScale;
```suggestion
 * [slider, 1.5] call ace_markers_fnc_onSliderPosChangedScale
```

2021-04-20 10:31 UTC, jonpas commented on addons/markers/functions/fnc_onSliderPosChangedScale.sqf
> + * Scale Slider Pos changed
```suggestion
 * Applies scale from on slider position change.
```

2021-04-20 10:31 UTC, jonpas approved these changes

2021-04-21 16:52 UTC, PabstMirror approved these changes

2021-04-21 20:36 UTC, merged