Medical - Show "Inventory" action on unconscious units
acemod/ACE3 pull request #8083
Opened 2021-01-26 05:06 UTC by Salluci

**When merged this pull request will:**
- See #8024.
- Adds "Inventory" action to unconscious units. Uses base Arma 3 inventory, action looks identical to vanilla action.

2021-01-26 13:43 UTC, BaerMitUmlaut requested changes
Please follow our [code style guidelines](https://ace3mod.com/wiki/development/coding-guidelines.html#5-code-style).

2021-01-26 14:33 UTC, veteran29 requested changes

2021-01-26 14:33 UTC, veteran29 commented on addons/medical_status/XEH_preInit.sqf
> +  private _id = _unit addAction [localize "STR_ACTION_GEAR", {
No point executing localize two times.
```suggestion
  private _id = _unit addAction ["", {
```

2021-03-03 19:15 UTC, BaerMitUmlaut approved these changes

2021-03-03 21:19 UTC, veteran29 approved these changes

2021-03-03 21:26 UTC, PabstMirror approved these changes

2021-03-03 21:30 UTC, PabstMirror commented
```
Run actions/upload-artifact@v2-preview
  with:
    name: ace3-23f6e044a073cabd39523b9584e51ed0b7129851-nobin
    path: releases/ace3_*.zip
With the provided path, there will be 1 files uploaded
Error: read ECONNRESET
```
failed check not-relevant

2021-03-03 21:30 UTC, merged