Dragging - Add more objects configs
acemod/ACE3 pull request #8104
Opened 2021-02-11 16:48 UTC by Dystopian

**When merged this pull request will:**
- add dragging configurations for frequent terrain objects (requires #8103);
- add default `Position` for missing config values;
- cleanup dragging config a little;
- change default draggable position from `[0,0,0]` (useless because it's inside player) to `[0,1.5,0]` (suits many objects);
- update documentation according to changes.

2021-04-20 10:47 UTC, jonpas requested changes
I think we can merge this right away if you split off terrain replacement config into that other existing PR.

2021-04-20 10:47 UTC, jonpas commented on docs/wiki/framework/dragging-framework.md
> +        ace_dragging_dragPosition[] = {0, 1.2, 0};  // Offset of the model from the body while dragging (same as attachTo) (optional; default: [0,1.5,0])
```suggestion
        ace_dragging_dragPosition[] = {0, 1.2, 0};  // Offset of the model from the body while dragging (same as attachTo) (optional; default: [0, 1.5, 0])
```

2021-04-20 10:47 UTC, jonpas commented on docs/wiki/framework/dragging-framework.md
> +        ace_dragging_carryPosition[] = {0, 1.2, 0};  // Offset of the model from the body while dragging (same as attachTo) (optional; default: [0,1,1])
```suggestion
        ace_dragging_carryPosition[] = {0, 1.2, 0};  // Offset of the model from the body while dragging (same as attachTo) (optional; default: [0, 1, 1])
```

2021-04-20 10:47 UTC, jonpas commented on docs/wiki/framework/dragging-framework.md
> +2  | Position to offset the object from player | Array | Optional (default: `[0,1.5,0]`)
```suggestion
2  | Position to offset the object from player | Array | Optional (default: `[0, 1.5, 0]`)
```

2021-04-20 10:47 UTC, jonpas commented on addons/dragging/functions/fnc_setDraggable.sqf
> +    _position = _object getVariable [QGVAR(dragPosition), [0,1.5,0]];
```suggestion
    _position = _object getVariable [QGVAR(dragPosition), [0, 1.5, 0]];
```

2021-04-20 10:47 UTC, jonpas commented on addons/dragging/functions/fnc_setDraggable.sqf
> + * 2: Position offset for attachTo command (optional; default: [0,1.5,0]) <ARRAY>
```suggestion
 * 2: Position offset for attachTo command (optional; default: [0, 1.5, 0]) <ARRAY>
```

2021-04-20 10:47 UTC, jonpas commented on addons/dragging/functions/fnc_initObject.sqf
> +    private _position = [_config >> QGVAR(carryPosition), "ARRAY", [0,1,1]] call CBA_fnc_getConfigEntry;
```suggestion
    private _position = [_config >> QGVAR(carryPosition), "ARRAY", [0, 1, 1]] call CBA_fnc_getConfigEntry;
```

2021-04-20 10:47 UTC, jonpas commented on addons/dragging/functions/fnc_initObject.sqf
> +    private _position = [_config >> QGVAR(dragPosition), "ARRAY", [0,1.5,0]] call CBA_fnc_getConfigEntry;
```suggestion
    private _position = [_config >> QGVAR(dragPosition), "ARRAY", [0, 1.5, 0]] call CBA_fnc_getConfigEntry;
```
Readability.

2021-05-03 10:38 UTC, Dystopian commented
I removed replacing config so this PR should be merged before #8103, then I re-add changes there.

I also added test code to description to create all new objects.

2021-05-03 10:47 UTC, jonpas approved these changes

2021-07-23 14:09 UTC, jonpas commented on docs/wiki/framework/dragging-framework.md
> +        ace_dragging_carryDirection = 0;  // Model direction while dragging (same as setDir after attachTo) (optional; default: 0)
```suggestion
        ace_dragging_carryDirection = 0;  // Model direction while dragging (same as setDir after attachTo) (default: 0)
```

2021-07-23 14:09 UTC, jonpas commented on docs/wiki/framework/dragging-framework.md
> +        ace_dragging_carryPosition[] = {0, 1.2, 0};  // Offset of the model from the body while dragging (same as attachTo) (optional; default: [0, 1, 1])
```suggestion
        ace_dragging_carryPosition[] = {0, 1.2, 0};  // Offset of the model from the body while dragging (same as attachTo) (default: [0, 1, 1])
```

2021-07-23 14:09 UTC, jonpas commented on docs/wiki/framework/dragging-framework.md
> +        ace_dragging_dragDirection = 0;  // Model direction while dragging (same as setDir after attachTo) (optional; default: 0)
```suggestion
        ace_dragging_dragDirection = 0;  // Model direction while dragging (same as setDir after attachTo) (default: 0)
```

2021-07-23 14:09 UTC, jonpas commented on docs/wiki/framework/dragging-framework.md
> +        ace_dragging_dragPosition[] = {0, 1.2, 0};  // Offset of the model from the body while dragging (same as attachTo) (optional; default: [0, 1.5, 0])
```suggestion
        ace_dragging_dragPosition[] = {0, 1.2, 0};  // Offset of the model from the body while dragging (same as attachTo) (default: [0, 1.5, 0])
```

2021-07-23 14:09 UTC, jonpas approved these changes

2021-07-23 14:11 UTC, merged