Interaction - Show all possible modes for an attachement
acemod/ACE3 pull request #8154
Opened 2021-03-07 20:04 UTC by PabstMirror

![image](https://user-images.githubusercontent.com/9376747/110253061-f421d780-7f4d-11eb-834f-c9593541df24.png)

2021-03-08 01:18 UTC, Dystopian commented
Tested, works. I would suggest to move these actions from `Detach` submenu to between `Attach` and `Detach` actions. It's much easier to select actions this way at least when menu is in list mode.

2021-03-08 04:22 UTC, mjc4wilton commented
> Tested, works. I would suggest to move these actions from `Detach` submenu to between `Attach` and `Detach` actions. It's much easier to select actions this way at least when menu is in list mode.

Maybe make it so it goes Weapon Attachments -> [Array of attachments] -> [Mode, Detach, etc.]?

2021-03-08 12:07 UTC, Dystopian requested changes

2021-03-08 12:07 UTC, Dystopian commented on addons/interaction/functions/fnc_getWeaponAttachmentsActions.sqf
> +            if (_x == _originalAttachment) then {continue};
```suggestion
            if (_x == _originalAttachment) then {continue};
            if (getText(_CBA_PIPItems >> _x) == _originalAttachment) then {continue};
```
CBA PIP optics should be ignored too. CUP has many scopes like this (e.g. ACOG and SUSAT).

2021-03-08 12:07 UTC, Dystopian commented on addons/interaction/functions/fnc_getWeaponAttachmentsActions.sqf
>      {
```suggestion
    private _CBA_PIPItems = configFile >> "CBA_PIPItems";
    {
```

2024-07-20 13:26 UTC, johnb432 commented
> Maybe make it so it goes Weapon Attachments -> [Array of attachments] -> [Mode, Detach, etc.]?

I fully agree with that, given we're adding some new actions. I went ahead and pushed the necessary changes.

Do we want to allow switching to PIP modes for scopes? To me it doesn't seem to be the worst idea, but I don't really use those scopes.

2024-07-20 13:38 UTC, johnb432 approved these changes
LGTM, but given I've rewritten part of the code, I'd like another person to take a second look at this.

2024-07-21 21:15 UTC, PabstMirror commented
![image](https://github.com/user-attachments/assets/939f5be6-9167-416e-9958-f9e964767bb2)

IMHO this might helpreadability to make the detach/attach sub-actions simpler
so they stand out from the switch action?

instead of `SPIR` -> `Detach: SPIR`
now just  `SPIR` -> `Detach`

2024-07-22 06:37 UTC, johnb432 commented
> IMHO this might helpreadability to make the detach/attach sub-actions simpler so they stand out from the switch action?
> 
> instead of `SPIR` -> `Detach: SPIR` now just `SPIR` -> `Detach`

Done.

2024-07-27 17:37 UTC, merged