Added ace_attach attached/detach events
acemod/ACE3 pull request #8193
Opened 2021-04-03 10:50 UTC by dedmen

Add local events for post-attach and pre-detach.
Pre-detach because you may want the object thats being detached before its deleted.
No post-detach as I don't see much use for it.

2021-04-03 12:39 UTC, bux commented on docs/wiki/framework/events-framework.md
> +|`ace_attach_attached` | [_attachedObject, _itemClassname] | Local | Listen | After a item was attached to Unit/Vehicle
```suggestion
|`ace_attach_attached` | [_attachedObject, _itemClassname] | Local | Listen | After an item was attached to a unit/vehicle
```

2021-04-03 12:40 UTC, bux commented on docs/wiki/framework/events-framework.md
> +|`ace_attach_detach` | [_attachedObject, _itemName] | Local | Listen | Just before a item gets detached/removed from Unit/Vehicle
```suggestion
|`ace_attach_detach` | [_attachedObject, _itemName] | Local | Listen | Just before an item gets detached/removed from a unit/vehicle
```

2021-04-17 17:04 UTC, PabstMirror approved these changes

2021-04-17 22:44 UTC, commy2 commented
Instead of
"attached" and "detach", maybe:
"attached" and "detaching"
?

2021-04-20 09:36 UTC, jonpas commented
I would prefer "detaching" as well, fits our verbiage better.

2021-04-20 09:37 UTC, jonpas requested changes

2021-04-20 09:37 UTC, jonpas commented on addons/attach/functions/fnc_detach.sqf
> +[QGVAR(detach), [_attachedObject, _itemName]] call CBA_fnc_localEvent;
```suggestion
[QGVAR(detaching), [_attachedObject, _itemName]] call CBA_fnc_localEvent;
```

2021-04-20 09:37 UTC, jonpas commented on docs/wiki/framework/events-framework.md
> +|`ace_attach_detach` | [_attachedObject, _itemName] | Local | Listen | Just before an item gets detached/removed from a unit/vehicle
```suggestion
|`ace_attach_detaching` | [_attachedObject, _itemName] | Local | Listen | Just before an item gets detached/removed from a unit/vehicle
```

2021-04-23 10:53 UTC, dedmen commented
Thanks @jonpas didn't have the time :u

2021-04-23 11:28 UTC, jonpas approved these changes

2021-04-26 16:56 UTC, PabstMirror approved these changes

2021-04-26 16:56 UTC, merged