WIP: Add Copperhead M712
acemod/ACE3 pull request #8210
Opened 2021-04-16 05:22 UTC by PabstMirror

Laser guided artillery round
- Can configure flight params via 3d object _(wouldn't it be neat if certain radio mods allowed this)_

Adds capability to missile guidance:
- Conditionally trigger a sub-munition (in this case it's launched as a shell and only extends wings at a pre-determined time, which triggers the original ammo and then continues the guidance on the new ammo object)
- Optionally use vanilla deflection via `setMissileTargetPos`

ToDo:
- [ ] Testing
- [ ] Localization
- [ ] Warhead stuff (it's a small shaped charge, probably reduce size of explosion)
- [ ] Tweak attack profile
- [ ] Documentation

Hoping to use some of this as a basis for more clgp/gravity bombs

2023-10-26 18:46 UTC, jonpas commented
> _(wouldn't it be neat if certain radio mods allowed this)_

Absolutely, where is the PR!? :joy:

2023-10-28 14:45 UTC, rautamiekka requested changes

2023-10-28 14:45 UTC, rautamiekka commented on addons/clgp/functions/fnc_copperhead_uiCreate.sqf
> +    } forEach [111, 112, 113,114, 115];
```suggestion
    } forEach [111, 112, 113, 114, 115];
```

2023-10-28 14:45 UTC, rautamiekka commented on addons/clgp/functions/fnc_copperhead_uiCreate.sqf
> +        if (!([_vehicle, ace_player] call FUNC(copperhead_uiCanOpen))) exitWith {
```suggestion
        if !([_vehicle, ace_player] call FUNC(copperhead_uiCanOpen)) exitWith {
```

2023-10-28 14:45 UTC, rautamiekka commented on addons/missileguidance/functions/fnc_onFiredDeferred.sqf
> +        // This was an AI shot, lets still guide it on the AI target
```suggestion
        // This was an AI shot, let's still guide it on the AI target
```

2023-10-28 14:45 UTC, rautamiekka commented on addons/missileguidance/functions/fnc_onFiredDeferred.sqf
> +if (_seekLastTargetPos && {!isNil "_target"}) then {
Surely the lazy eval doesn't save anything with such a cheap check (on another var, no less) ?
```suggestion
if (_seekLastTargetPos && !isNil "_target") then {
```

2023-10-28 14:45 UTC, rautamiekka commented on addons/missileguidance/functions/fnc_onFiredDeferred.sqf
> +        ];
```suggestion
    [   _shooter,
        [_target, _targetPos, _launchPos],
        _seekerType,
        _attackProfile,
        _lockMode,
        _laserInfo
    ],
    [
        getNumber ( _config >> "minDeflection" ),
        getNumber ( _config >> "maxDeflection" ),
        getNumber ( _config >> "incDeflection" ), // not used?
        1 == getNumber ( _config >> "useVanillaDeflection" )
    ],
    [
        getNumber ( _config >> "seekerAngle" ),
        getNumber ( _config >> "seekerAccuracy" ),
        getNumber ( _config >> "seekerMaxRange" ),
        getNumber ( _config >> "seekerMinRange" )
    ],
    [ diag_tickTime, [], [], _lastKnownPosState ]
];
```

2023-10-28 14:45 UTC, rautamiekka commented on addons/clgp/functions/fnc_copperhead_uiCreate.sqf
> +        if ((!alive _vehicle) || {_settings isEqualTo []}) exitWith { ERROR_2("unloaded with bad input %1-%2",_vehicle,_settings); };
Surely the lazy eval doesn't save anything with such a cheap check ?
```suggestion
        if ((!alive _vehicle) || _settings isEqualTo []) exitWith { ERROR_2("unloaded with bad input %1-%2",_vehicle,_settings); };
```

2023-10-28 14:45 UTC, rautamiekka commented on addons/clgp/functions/fnc_copperhead_uiCanOpen.sqf
> +        if ((_xTurret isEqualTo [0]) && {_xAmmo > 0} && {_xMag == "ace_1rnd_155mm_m712"}) exitWith {
Surely the lazy eval don't save anything with such cheap checks ?
```suggestion
&& alive _vehicle
&& {
    private _hasCopperheadAmmo = false;
    {
        _x params ["_xMag", "_xTurret", "_xAmmo"];
        if ((_xTurret isEqualTo [0]) && _xAmmo > 0 && {_xMag == "ace_1rnd_155mm_m712"}) exitWith {
```

2023-10-28 14:45 UTC, rautamiekka commented on addons/clgp/functions/fnc_copperhead_attackprofile.sqf
> +    if (_isFalling && {!_trajectoryBallistic}) then {
Surely the lazy eval doesn't save anything with such a cheap check ?
```suggestion
    if (_isFalling && !_trajectoryBallistic) then { 
```

2023-10-28 14:45 UTC, rautamiekka commented on addons/clgp/XEH_postInit.sqf
> +    if (currentWeapon _veh == "mortar_155mm_AMOS") then {
```suggestion
    if (currentWeapon _veh isEqualTo "mortar_155mm_AMOS") then {
```
If `currentWeapon` always returns the correct casing.

2023-10-28 14:45 UTC, rautamiekka commented on addons/clgp/XEH_postInit.sqf
> +        if ((!alive _player) || {!alive _vehicle} || {_vehicle getVariable [QGVAR(copperhead_actionHandled), false]}) exitWith { TRACE_1("exit",_vehicle); };
Surely the lazy eval doesn't save anything with such a cheap check ?
```suggestion
        if ((!alive _player) || !alive _vehicle || {_vehicle getVariable [QGVAR(copperhead_actionHandled), false]}) exitWith { TRACE_1("exit",_vehicle); };
```

2024-05-24 16:03 UTC, rautamiekka requested changes

2024-05-24 16:03 UTC, rautamiekka commented on addons/clgp/functions/fnc_copperhead_onfired.sqf
> +// private _trajectoryShaped = _trajectorySetting >= 3; // 1-2 is ballisitic, 3-8 is shaped
```suggestion
// private _trajectoryShaped = _trajectorySetting >= 3; // 1-2 is ballistic, 3-8 is shaped
```

2024-05-24 16:03 UTC, rautamiekka commented on addons/clgp/script_component.hpp
> +#define COMPONENT_BEAUTIFIED Cannon Launched Guided Projectiles
```suggestion
#define COMPONENT_BEAUTIFIED Cannon-Launched Guided Projectiles
```

2025-01-13 21:11 UTC, PabstMirror commented on addons/missile_clgp/CfgAmmo.hpp
> +            maxDeflection = 0.001;       // Maximum flap deflection for guidance
update for MG changes, eg:
```
    pitchRate = 15; // replace minDeflection, maxDeflection, incDeflection
    yawRate = 15;
    defaultNavigationType = "Direct";
    navigationTypes[] = { "Direct" };
```

2025-01-29 15:01 UTC, TheCandianVendingMachine commented on addons/missile_clgp/functions/fnc_copperhead_attackprofile.sqf
> +#ifdef DEBUG_MODE_FULL
I would personally like if this was predicated on `ace_missileguidance_debug_drawGuidanceInfo`, but not a blocker

2025-01-29 15:01 UTC, TheCandianVendingMachine commented on addons/missile_clgp/functions/fnc_copperhead_uiCanOpen.sqf
> +        if ((_xTurret isEqualTo [0]) && {_xAmmo > 0} && {_xMag == "ace_1rnd_155mm_m712"}) exitWith {
can we throw a config entry into `ace_missileguidance` so we aren't hard coded into the ammo type? or is there too many things specific about this magazine that we need this

2025-02-18 06:58 UTC, PabstMirror commented on addons/missile_clgp/CfgAmmo.hpp
> +        EGVAR(frag,charge) = 9979;
wiki and func say it's in grams not kg?
> Amount of explosive filler (grams) - information below

there seems to be some inconsistencies in ace as well

2025-03-02 22:11 UTC, TheCandianVendingMachine approved these changes
g2g, tested a previous version and guidance worked well. probably affected by #10715  but that will require a MG change, not relevant to this PR

2025-03-02 22:17 UTC, merged