partial #8230
acemod/ACE3 pull request #8231
Opened 2021-04-24 19:23 UTC by irvnriir

**When merged this pull request will:**
- Add support for `curatorSelected` processing

2021-04-24 21:02 UTC, BaerMitUmlaut requested changes
Congrats, not a single line that was acceptable. That's a first.

2021-04-24 21:02 UTC, BaerMitUmlaut commented on addons/zeus/functions/fnc_ui_defendArea.sqf
> +	}forEach _g_sc;
Again, what's with the formatting?

2021-04-24 21:02 UTC, BaerMitUmlaut commented on addons/zeus/functions/fnc_ui_defendArea.sqf
> +	};
Wrong indentation.

2021-04-24 21:02 UTC, BaerMitUmlaut commented on addons/zeus/functions/fnc_ui_defendArea.sqf
> +_control ctrlAddEventHandler ["ButtonClick", _this + [_g_sc] call _fnc_onConfirm];
Since in your params you expect `_g_sc` to be part of `_this`, this doesn't make any sense to me.

2021-04-24 21:04 UTC, BaerMitUmlaut commented
Since none of this can be merged at this point and you didn't even make the effort of naming your PR in a sensible way, I'm closing this. Feel free to reopen it once you've got this in an acceptable state.

2021-04-24 21:04 UTC, closed without merging

2021-04-24 21:18 UTC, irvnriir commented
i'm sor that you wasted the time to describe . but this shitty and nonsense code structure already bothered me too much to put any more time in (even reading/examining it took too much effort, not even counting including the feature) . the feature is very simple, and this my example should work . include it if you don't mind .

2021-04-25 14:36 UTC, commy2 commented
This PR broke my game.