Aircraft - Drone Tools
acemod/ACE3 pull request #8276
Opened 2021-06-02 23:19 UTC by PabstMirror

- Allows quickly changing UAV waypoints from gunner seat
 Modify loiter radius, altitude and direction
 Setting defaults to on because this is all stuff you can do from the terminal, just easier
- Draws laser designator on the map
Close https://github.com/KoffeinFlummi/AGM/pull/1903 😄 
Setting defaults off. Most drones already list the grid cords, this is just QOL

https://www.youtube.com/watch?v=8vF_b2aJ12s

2021-06-03 06:46 UTC, Dystopian requested changes
I think there is no reason to disable these tools so settings are not needed.

2021-06-03 06:46 UTC, Dystopian commented on addons/aircraft/functions/fnc_droneAddMapHandler.sqf
> +        ((getDir _laserTarget) + 90)];
```suggestion
            "\A3\ui_f\data\igui\rscingameui\rscoptics\laser_designator_iconLaserOn.paa",
            [1,0,1,1],
            (getPos _laserTarget),
            16, 16,
            ((getDir _laserTarget) + 90)
        ];
```

2021-06-09 21:25 UTC, TheCandianVendingMachine commented
Would it be possible to extend this for all aircraft types? I'd like to see a target on the map for helicopters and jets as well

2022-05-04 23:55 UTC, jonpas approved these changes

2022-05-05 16:07 UTC, merged