Captives - Add caller to captiveStatusChanged event
acemod/ACE3 pull request #8360
Opened 2021-08-06 04:59 UTC by Salluci

**When merged this pull request will:**
- Title.
- Addresses #8259.

2021-08-22 15:01 UTC, veteran29 requested changes

2021-08-22 15:01 UTC, veteran29 commented on addons/captives/functions/fnc_doRemoveHandcuffs.sqf
Please update the function example.

2021-08-22 23:16 UTC, veteran29 approved these changes

2021-08-23 17:46 UTC, PabstMirror commented on addons/captives/functions/fnc_doApplyHandcuffs.sqf
> +[QGVAR(setHandcuffed), [_target, true, _caller], [_target]] call CBA_fnc_targetEvent;
`_caller` isn't defined, I think this should just be `_unit`
```suggestion
[QGVAR(setHandcuffed), [_target, true, _unit], [_target]] call CBA_fnc_targetEvent;
```

2021-08-23 17:46 UTC, PabstMirror commented on addons/captives/functions/fnc_doRemoveHandcuffs.sqf
> +[QGVAR(setHandcuffed), [_target, false, _caller], [_target]] call CBA_fnc_targetEvent;
```suggestion
[QGVAR(setHandcuffed), [_target, false, _unit], [_target]] call CBA_fnc_targetEvent;
```

2021-08-23 17:51 UTC, PabstMirror commented on addons/captives/functions/fnc_doApplyHandcuffs.sqf
> +[QGVAR(setHandcuffed), [_target, true, _caller], [_target]] call CBA_fnc_targetEvent;
or a better fix might be to change all other refs of `_unit` to `_caller` to keep consistancy with setHandcuffed

2021-08-23 20:09 UTC, PabstMirror approved these changes

2021-09-03 19:38 UTC, merged

2021-10-10 17:03 UTC, mwpowellhtx commented
Beautiful, thank you.