Adding option to disable screaming for units on fire
acemod/ACE3 pull request #8665
Opened 2021-11-05 11:47 UTC by Crowdedlight

**When merged this pull request will:**
Add a CBA setting that can disable/enable the screaming sounds when units are on fire. Solves https://github.com/acemod/ACE3/issues/8664 

Adds a CBA setting.
Adds check in "playScream" event before playing the screams.

2021-11-05 12:10 UTC, veteran29 requested changes

2021-11-05 12:10 UTC, veteran29 commented on addons/fire/initSettings.sqf
> +] call CBA_fnc_addSetting;
missing trailing newline
```suggestion
] call CBA_fnc_addSetting;

```

2021-11-05 12:10 UTC, veteran29 commented on addons/fire/initSettings.sqf
> +    [LSTRING(Setting_EnableScreams), LSTRING(Setting_EnableScreamsDescription)],
```suggestion
    [LSTRING(Setting_EnableScreams), LSTRING(Setting_EnableScreams_Description)],
```

2021-11-05 12:10 UTC, veteran29 commented on addons/fire/stringtable.xml
> +        <Key ID="STR_ACE_Fire_Setting_EnableScreamsDescription">
```suggestion
        <Key ID="STR_ACE_Fire_Setting_EnableScreams_Description">
```

2021-11-05 18:17 UTC, PabstMirror approved these changes

2021-11-05 18:27 UTC, veteran29 approved these changes

2021-11-07 09:05 UTC, commy2 approved these changes

2021-11-07 23:32 UTC, merged