Fire - Add ellipsis & decapitalize 'patting down fire' string
acemod/ACE3 pull request #8753
Opened 2021-12-22 10:10 UTC by Salluci

**When merged this pull request will:**
- Title.

### IMPORTANT

- [ ] If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3mod.com/).
- [x] [Development Guidelines](https://ace3mod.com/wiki/development/) are read, understood and applied.
- [x] Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2021-12-22 10:20 UTC, Salluci commented
Uhh, pboProject, are you okay?

2021-12-22 10:47 UTC, jonpas approved these changes

2022-01-05 19:04 UTC, PabstMirror approved these changes

2022-01-05 19:09 UTC, BrettMayson requested changes

2022-01-05 19:09 UTC, BrettMayson commented on addons/fire/stringtable.xml
> +            <Japanese>火を叩き消しています...</Japanese>
```suggestion
            <Japanese>火を叩き消しています・・・</Japanese>
```

2022-01-06 05:10 UTC, merged