UI - Make Speed Indicator independent of 'Show Stance Info' difficulty setting
acemod/ACE3 pull request #8760
Opened 2021-12-24 12:44 UTC by Salluci

**When merged this pull request will:**
- Move speed indicator control into its own separate container, like Advanced Fatigue's Stamina Bar.

### IMPORTANT

- [ ] If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3mod.com/).
- [x] [Development Guidelines](https://ace3mod.com/wiki/development/) are read, understood and applied.
- [x] Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2021-12-24 20:02 UTC, veteran29 requested changes
As the indicator is not tied to unit info container now, the indicator will stay there when you enter the vehicle while moving.
![image](https://user-images.githubusercontent.com/4293906/147370994-785e9600-1b1c-42c6-bc0d-8b2bd6eb84f6.png)

2021-12-24 20:06 UTC, veteran29 requested changes

2021-12-24 20:06 UTC, veteran29 commented on addons/ui/functions/fnc_createSpeedIndicator.sqf
> +_speedIndicator ctrlCommit 0;
Is there a need to fade this at all? When the indicator is disabled the whole container is hidden anyway.

2021-12-24 20:06 UTC, veteran29 commented on addons/ui/functions/fnc_handleSpeedIndicator.sqf
> +_speedIndicatorContainer ctrlCommit 0
I see no need to "unfade" the indicator on every animation change. As this code runs "all the time" due to changing animations I would prefer for it to be as fast as possible. 

Also I would suggest to store the indicator itself in the uiNamspace so there will be no need for `controlsGroupCtrl `.

2021-12-25 21:14 UTC, Salluci commented
Working on modular alternate solution. Closing.

2021-12-25 21:14 UTC, closed without merging