nametags - Fix ACE nametag drawIcon3D parameter error when player controlled unit dies
acemod/ACE3 pull request #8764
Opened 2021-12-30 12:51 UTC by Vdauphin

**When merged this pull request will:**
- fix #8719 
- Make sure `_icon` is never `nil`

### IMPORTANT

- [ ] If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3mod.com/).
- [ ] [Development Guidelines](https://ace3mod.com/wiki/development/) are read, understood and applied.
- [ ] Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2021-12-30 15:14 UTC, commy2 commented
This function is horrenduous. While this probably fixes the issue, it only makes the thing even worse. I'd prefer if someone refactors this.

2021-12-30 15:28 UTC, Vdauphin commented
No time here to rewrite it.

2021-12-31 09:30 UTC, commy2 requested changes
This breaks object namespace icons. As suspected, the logic is broken.

2021-12-31 09:39 UTC, commy2 commented
```sqf
    params ["_player", "_target", "_alpha", "_heightOffset", "_drawName", "_drawRank", "_drawSoundwave"];

    private _targetIcon = _target getVariable QGVAR(rankIcon);

    private _icon = switch true do {
        case _drawSoundwave: {
            format [QPATHTOF(UI\soundwave%1.paa), floor random 10]
        };

        case !_drawRank: {""};

        case !isNil "_targetIcon": {_targetIcon};

        case rank _target != "": {
            private _targetFaction = _target getVariable [QGVAR(faction), faction _target];
            private _customRankIcons = GVAR(factionRanks) getVariable _targetFaction;

            if (!isNil "_customRankIcons") then {
                _customRankIcons param [ALL_RANKS find rank _target, ""] // return
            } else {
                // default rank icons
                format ["\A3\Ui_f\data\GUI\Cfg\Ranks\%1_gs.paa", rank _target] // return
            };
        };

        default {""};
    };
```

2022-02-06 14:58 UTC, Salluci commented
Does this need testing?

2022-02-06 19:18 UTC, Vdauphin commented
I tested after committing if I remember correctly

2022-02-08 20:38 UTC, Salluci commented on addons/nametags/functions/fnc_drawNameTagIcon.sqf
> +        case rank _target == "": {""};
Getting a script error when approaching players in this line. Maybe this needs to be put inside parenthesis?

2022-02-08 22:51 UTC, Vdauphin commented
Tested when getting closer to unit and when units get killed

2022-03-07 18:26 UTC, merged