Translations - Add german translations
acemod/ACE3 pull request #8771
Opened 2022-01-10 20:22 UTC by EduardSchwarzkopf

**When merged this pull request will:**
- Add german translations in `common` module
- Add german translations in `fortify` module
- Add german translations in `fire` module
- Add german translations in `slideshow` module
- Add german translations in `viewdistance` module

This my very first pull request, please provide any feedback if I can make improvements on something in this process.

Thanks

2022-01-11 06:11 UTC, bux commented
Very refreshing to see a translation PR that gets all the basic orthography and grammar right. So thank you very much! 😄

2022-01-11 06:11 UTC, bux requested changes

2022-01-11 06:11 UTC, bux commented on addons/fortify/stringtable.xml
> +            <German>Für Einheiten, die freundlich zum Platzierer stehen.</German>
"Freundlich" passt nicht wirklich. Eher "befreundet". Außer "Verbündete" fällt mir hier kein guter Begriff ein. Wobei "Verbündet" eine deutlich engere Beziehung als nur "befreundet" widerspiegelt.

2022-01-11 06:11 UTC, bux commented on addons/overheating/stringtable.xml
> +            <German>Koeffizient, der angibt, wie viel zusätzliche Wärme durch das Anbringen eines Schalldämpfers hinzugefügt wird. Ein höherer Wert erhöht die Wärme, 0 bedeutet keine zusätzliche Wärm
```suggestion
            <German>Koeffizient, der angibt, wie viel zusätzliche Wärme durch das Anbringen eines Schalldämpfers hinzugefügt wird. Ein höherer Wert erhöht die Menge an Wärme, 0 bedeutet, dass keine zusätzliche Wärme durch den Schalldämpfer hinzukommt.</German>
```

2022-01-11 06:17 UTC, EduardSchwarzkopf commented on addons/fortify/stringtable.xml
> +            <German>Für Einheiten, die freundlich zum Platzierer stehen.</German>
Gebe ich recht, werde ich anpassen

2022-01-11 06:23 UTC, EduardSchwarzkopf commented on addons/fortify/stringtable.xml
> +            <German>Für Einheiten, die freundlich zum Platzierer stehen.</German>
Meinst du "Ersteller" ist ebenfalls die bessere Wahl, anstelle "Platzierer"?

2022-01-12 04:37 UTC, bux approved these changes

2022-01-12 18:35 UTC, merged