ADD - Missile Guidance - Spike LR ATGM
acemod/ACE3 pull request #8931
Opened 2022-06-03 02:35 UTC by TheCandianVendingMachine

**When merged this pull request will:**
- Adds Spike LR ATGM
- Adds custom camera framework for Spike to use

Requires #8215

2022-06-03 12:29 UTC, rautamiekka commented on addons/spike/functions/fnc_camera_switchAway.sqf
> +  * Author: Dani (TCVM)
```suggestion
 * Author: Dani (TCVM)
```

2022-06-03 12:29 UTC, rautamiekka commented on addons/spike/functions/fnc_camera_switchTo.sqf
> +  * Author: Dani (TCVM)
```suggestion
 * Author: Dani (TCVM)
```

2022-06-03 12:34 UTC, rautamiekka commented on addons/spike/functions/fnc_camera_update.sqf
> +        if !(_lastGroundPos isEqualTo [0, 0, 0]) then {
```suggestion
        if (_lastGroundPos isNotEqualTo [0, 0, 0]) then {
```

2022-06-03 12:36 UTC, rautamiekka commented on addons/spike/functions/fnc_camera_updateTargetingGate.sqf
> +  * Author: Dani (TCVM)
```suggestion
 * Author: Dani (TCVM)
```

2022-06-03 12:37 UTC, rautamiekka commented on addons/spike/functions/fnc_camera_userInCamera.sqf
> +  * Author: Dani (TCVM)
```suggestion
 * Author: Dani (TCVM)
```

2022-06-03 12:40 UTC, rautamiekka commented on addons/spike/functions/fnc_onFired.sqf
> +if (!(_cameraConfig isEqualTo configNull) && { (getNumber (_cameraConfig >> "enabled")) == 1 }) then {
```suggestion
if ((_cameraConfig isNotEqualTo configNull) && { (getNumber (_cameraConfig >> "enabled")) == 1 }) then {
```

2024-05-28 03:36 UTC, TheCandianVendingMachine commented
Updated to merge into new missile guidance branch

2024-08-23 14:23 UTC, PabstMirror commented
guess it auto closed because target merged, ugh

2024-08-23 14:42 UTC, PabstMirror commented
reopen test

2024-08-30 13:59 UTC, johnb432 requested changes
All headers to `camera` functions (and some others) need to be updated with correct examples.

2024-08-30 13:59 UTC, johnb432 commented on addons/spike/XEH_postInit.sqf
> +    }*/] call EFUNC(interact_menu,createAction);
This shouldn't stay commented as it is.

2024-08-30 13:59 UTC, johnb432 commented on addons/spike/functions/fnc_camera_update.sqf
> +    if !((_movingCameraX || _movingCameraY) || true) then {
That `true` needs to go.

2024-08-30 13:59 UTC, johnb432 commented on addons/spike/functions/fnc_camera_update.sqf
> +private _p = _cameraPosASL vectorAdd _relativePos;
`_p` should be replaced with a better variable name.

2024-08-30 13:59 UTC, johnb432 commented on addons/spike/stringtable.xml
> +            <English>Leave Camera</English><!-- Check this -->
Comments need to be addressed and removed.

2024-08-30 13:59 UTC, johnb432 commented on addons/spike/script_component.hpp
> + #define DISABLE_COMPILE_CACHE
```suggestion
 // #define DISABLE_COMPILE_CACHE
```

2024-08-31 01:38 UTC, rautamiekka requested changes

2024-08-31 01:38 UTC, rautamiekka commented on addons/spike/functions/fnc_camera_cycleViewMode.sqf
> + * Cycles camera thermal mode (if avaliable)
```suggestion
 * Cycles camera thermal mode (if available)
```

2024-08-31 01:38 UTC, rautamiekka commented on addons/spike/functions/fnc_camera_init.sqf
> +private _projectileBounds = (1 boundingBoxReal _projectile);
```suggestion
private _projectileBounds = 1 boundingBoxReal _projectile;
```

2024-08-31 01:38 UTC, rautamiekka commented on addons/spike/functions/fnc_camera_switchTo.sqf
> +if ([] call FUNC(camera_userInCamera)) exitWith {};
```suggestion
if ([] call FUNC(camera_userInCamera)) exitWith {};

params ["_cameraNamespace"];
```

2024-08-31 01:38 UTC, rautamiekka commented on addons/spike/functions/fnc_camera_update.sqf
> +    if !((_movingCameraX || _movingCameraY) || true) then {
```suggestion
    if !(_movingCameraX || _movingCameraY) then {
```

2024-08-31 01:38 UTC, rautamiekka commented on addons/spike/functions/fnc_camera_update.sqf
> +        if (_trackLockedPosition && { (_seekerTargetPos isNotEqualTo [0, 0, 0]) } && _canStopDesignating) then {
```suggestion
        if (_trackLockedPosition && _canStopDesignating && { _seekerTargetPos isNotEqualTo [0, 0, 0] }) then {
```

2024-08-31 01:38 UTC, rautamiekka commented on addons/spike/functions/fnc_camera_userInCamera.sqf
> +if (isNil QGVAR(activeCamera)) exitWith { false };
```suggestion
if (isNil QGVAR(activeCamera)) exitWith { false };

params [["_cameraNamespace", objNull]];
```

2024-08-31 01:38 UTC, rautamiekka commented on addons/spike/functions/fnc_keyDown.sqf
> +if ((currentWeapon ACE_player) != QGVAR(launcher)) exitWith {};
```suggestion
if ((currentWeapon ACE_player) != QGVAR(launcher)) exitWith {};

params ["_key", "_down"];
```

2024-08-31 01:38 UTC, rautamiekka commented on addons/spike/functions/fnc_keyDown.sqf
> +    if (cameraView == "GUNNER") then {
```suggestion
    if (cameraView isEqualTo "GUNNER") then {
```

2024-08-31 01:38 UTC, rautamiekka commented on addons/spike/functions/fnc_onFired.sqf
> +        getNumber (_cameraConfig >> "gimbal" >> "trackLockedPosition") == 1
Ouch, this many calls has to be expensive.
```suggestion
    private _cameraConfigGimbal = _cameraConfig >> "gimbal";
    _cameraArray set [9, [
        getNumber (_cameraConfigGimbal >> "enabled") == 1,
        getNumber (_cameraConfigGimbal >> "gimbalAngleX"),
        getNumber (_cameraConfigGimbal >> "gimbalAngleY"),
        getNumber (_cameraConfigGimbal >> "gimbalSpeedX"),
        getNumber (_cameraConfigGimbal >> "gimbalSpeedY"),
        getNumber (_cameraConfigGimbal >> "gimbalInitOffsetX"),
        getNumber (_cameraConfigGimbal >> "gimbalInitOffsetY"),
        getArray (_cameraConfigGimbal >> "fovGimbalSpeedModifiers"),
        getNumber (_cameraConfigGimbal >> "stabilizeWhenMoving") == 1,
        getNumber (_cameraConfigGimbal >> "designateWhenStationary") == 1,
        getNumber (_cameraConfigGimbal >> "trackLockedPosition") == 1
```

2024-08-31 01:38 UTC, rautamiekka commented on addons/spike/functions/fnc_onFired.sqf
> +        getNumber (_cameraConfig >> "reticle" >> "reticleMovesWithTrack") == 1
```suggestion
    private _cameraConfigReticle = _cameraConfig >> "reticle";
    _cameraArray set [10, [
        getText (_cameraConfigReticle >> "titleRsc"),
        getNumber (_cameraConfigReticle >> "centerReticle"),
        getArray (_cameraConfigReticle >> "controlsToDisappearOnLock"),
        getArray (_cameraConfigReticle >> "controlsToAppearOnLock"),
        getNumber (_cameraConfigReticle >> "leftGate"),
        getNumber (_cameraConfigReticle >> "rightGate"),
        getNumber (_cameraConfigReticle >> "topGate"),
        getNumber (_cameraConfigReticle >> "bottomGate"),
        getText (_cameraConfigReticle >> "uiNamespaceDialogVariable"),
        getNumber (_cameraConfigReticle >> "reticleMovesWithTrack") == 1
```

2025-03-10 20:27 UTC, PabstMirror commented on addons/spike/initKeybinds.inc.sqf
> +[200, [false, false, false]], false] call CBA_fnc_addKeybind;  //Up Arrow
To me it makes sense for this and MCLOS to have the same keys, but I'm not sure

```suggestion
[DIK_NUMPAD8, [false, false, false]], false] call CBA_fnc_addKeybind;  // Numpad 8
```

2025-03-25 16:08 UTC, PabstMirror commented on addons/spike/initKeybinds.inc.sqf
> +[200, [false, false, false]], false] call CBA_fnc_addKeybind;  //Up Arrow
I will try to update this to use the new "unified" keybind system
Possibly also look to combine the "lock key" (tab)

2025-06-14 12:09 UTC, johnb432 commented on addons/spike/ACE_GuidanceConfig.hpp
> +class ace_missileguidance_SeekerTypes {
```suggestion
class EGVAR(missileguidance,SeekerTypes) {
```

2025-06-14 12:09 UTC, johnb432 commented on addons/spike/ACE_GuidanceConfig.hpp
> +class ace_missileguidance_NavigationTypes {
```suggestion
class EGVAR(missileguidance,NavigationTypes) {
```

2025-06-14 12:13 UTC, johnb432 commented on addons/spike/XEH_PREP.hpp
> +PREP(getTargetPosition);
```suggestion
PREP(getTargetPosition);
PREP(keyDown);
PREP(mapHelperDraw);
PREP(midCourseTransition);
PREP(navigation);
PREP(onFired);
PREP(seeker);
```

2025-06-14 12:17 UTC, johnb432 commented on addons/spike/initKeybinds.inc.sqf
> +["ACE3 Weapons", QGVAR(Designate), LLSTRING(Designate),
```suggestion
#include "\a3\ui_f\hpp\defineDIKCodes.inc"

["ACE3 Weapons", QGVAR(Designate), LLSTRING(Designate),
```

2025-06-14 12:18 UTC, johnb432 commented on addons/spike/initKeybinds.inc.sqf
> +[15, [false, false, false]], false] call CBA_fnc_addKeybind;  // Tab
```suggestion
[DIK_TAB, [false, false, false]], false] call CBA_fnc_addKeybind;  // Tab
```

2025-06-14 12:18 UTC, johnb432 commented on addons/spike/initKeybinds.inc.sqf
> +[15, [false, true, false]], false] call CBA_fnc_addKeybind;  // Ctrl+Tab
```suggestion
[DIK_TAB, [false, true, false]], false] call CBA_fnc_addKeybind;  // Ctrl+Tab
```

2025-06-14 12:18 UTC, johnb432 commented on addons/spike/initKeybinds.inc.sqf
> +[49, [false, false, false]], false] call CBA_fnc_addKeybind;  //N
```suggestion
[DIK_N, [false, false, false]], false] call CBA_fnc_addKeybind;  //N
```

2025-06-14 12:19 UTC, johnb432 commented on addons/spike/initKeybinds.inc.sqf
> +[78, [false, false, false]], false] call CBA_fnc_addKeybind;  //Keypad+
```suggestion
[DIK_ADD, [false, false, false]], false] call CBA_fnc_addKeybind;  //Keypad+
```

2025-06-14 12:19 UTC, johnb432 commented on addons/spike/initKeybinds.inc.sqf
> +[74, [false, false, false]], false] call CBA_fnc_addKeybind;  //Keypad-
```suggestion
[DIK_SUBTRACT, [false, false, false]], false] call CBA_fnc_addKeybind;  //Keypad-
```

2025-06-14 12:19 UTC, johnb432 commented on addons/spike/functions/fnc_onFired.sqf
> +params ["_firedEH"];
Personally, I'd prefer if there were a space between the header and the first line of code.
```suggestion

params ["_firedEH"];
```

2025-06-22 07:12 UTC, johnb432 approved these changes
I haven't checked the functionality, but code formatting looks good.

2025-06-22 15:24 UTC, merged

2025-06-28 13:53 UTC, mrschick commented
Got around to testing it a bit.
It seems really hard to lock onto distant targets (especially off-bore), mainly due to the digital inputs' high sensitivity.
Surely IRL it would have an analog input or a cumulative effect for the digital input. I could look into implementing the latter.

EDIT:
Zooming in thankfully makes slewing onto a target much easier.
Unfortunately there appear to be some guidance issues when engaging distant targets moving at high speed. The missile tries at all costs to overfly the target before flying down onto it, but if energy is insufficient to do so, it will stall out and miss, instead of falling back to a pure-pursuit and maintaining a max range glide attitude.