Medical Treatment - Add Additional Conditions for PAK Use
acemod/ACE3 pull request #8964
Opened 2022-07-12 13:54 UTC by dgibso29

**When merged this pull request will:**
Personal Aid Kits now have additional optional conditions for use:
- Minimum Blood Level
- Minimum Heart Rate
- Patient must not be in pain
- Patient must have no untreated fractures
- Patient must have no open wounds
- Patient must have no open or bandaged wounds (Must be fully stitched)

This PR is an attempt to resuscitate the work done in stale PR #7684, which was created prior to major build pipeline changes. The actual feature work has been recreated and re-tested here.

### IMPORTANT

- [x] If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [x] [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- [x] Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2022-07-12 17:45 UTC, Cre8or commented
It seems reasonable to give mission makers more control over the "embedded" aspects of ACE's medical system. Without PRs like these, communities have to resort to making in-house mods to expose the underlying features as CBA options. Which is fine if you only have to do this for one mod, but repeat that process a few times and your addon dependency graph quickly becomes more intricate than the lineage of the British royal family.

Jokes aside - I appreciate your dedication for keeping this submission going, and hope this gets more attention this time! 🤞

2022-07-16 11:31 UTC, Joecuronium commented
As a missionmaker I would very much appreciate this being added, since currently I don't give out PAKs since it represents an "auto-heal" button in an otherwise pretty realistic representation of how med-care should work.
Tying the PAK to a condition would allow to be an actual tool that rewards proper care by lower-tier medics until the pt can be seen ba a doc.

2022-10-12 23:09 UTC, rautamiekka commented on addons/medical_status/functions/fnc_isInStableCondition.sqf
> +private _hasOpenWounds = (GET_OPEN_WOUNDS(_unit) findIf {_x select 2 > 0 && _x select 3 > 0} ) != -1;
```suggestion
private _hasOpenWounds = (GET_OPEN_WOUNDS(_unit) findIf {_x select 2 > 0 && {_x select 3 > 0}}) != -1;
```

2022-10-13 00:07 UTC, dgibso29 commented on addons/medical_status/functions/fnc_isInStableCondition.sqf
> +private _hasOpenWounds = (GET_OPEN_WOUNDS(_unit) findIf {_x select 2 > 0 && _x select 3 > 0} ) != -1;
Good shout, thanks.

2022-10-13 00:39 UTC, dgibso29 commented on addons/medical_status/functions/fnc_isInStableCondition.sqf
> +if (EGVAR(medical_treatment,allowFracturesPAK) == 0 && { ((GET_FRACTURES(_unit) findIf {_x isEqualTo 1}) != -1) })  exitWith {false};
Added an additional option to allow fractures to prevent PAK use.

2022-10-13 00:50 UTC, dgibso29 commented
Current state of PR has been successfully tested on dedicated server.

2022-10-22 17:59 UTC, rautamiekka approved these changes
What little I know about ACE's workings it's good, I'll leave the rest to others.

2023-03-07 19:40 UTC, dgibso29 commented
@rautamiekka Just bumping this as it seems to be falling under the radar. Thanks for any context you can provide.

2023-03-19 22:40 UTC, dgibso29 commented
@veteran29 Apologies for the ping, but you have been active in the repository recently and am trying to get movement on this PR. These changes have been approved in the past and gone through several rounds of feedback from @mharis001, but it seems to be falling under the radar since.

Thanks!

2023-05-16 05:37 UTC, BrettMayson approved these changes

2023-06-28 10:51 UTC, LinkIsGrim requested changes

2023-06-28 10:51 UTC, LinkIsGrim commented on addons/medical_status/functions/fnc_isInStableCondition.sqf
> +if (EGVAR(medical_treatment,allowFracturesPAK) == 0 && { ((GET_FRACTURES(_unit) findIf {_x isEqualTo 1}) != -1) })  exitWith {false};
```suggestion
if (EGVAR(medical_treatment,allowFracturesPAK) == 0 && {1 in (GET_FRACTURES(_unit))})  exitWith {false};
```

Minor optimization.

2023-06-28 10:51 UTC, LinkIsGrim commented on addons/medical_status/functions/fnc_isInStableCondition.sqf
> +private _hasOpenWounds = (GET_OPEN_WOUNDS(_unit) findIf {_x select 2 > 0 && {_x select 3 > 0}}) != -1;
Needs to be updated for #8926.

2023-06-28 10:51 UTC, LinkIsGrim commented on addons/medical_treatment/initSettings.sqf
IMO this should be moved to its own category, but out of scope for this PR.

2023-06-28 10:51 UTC, LinkIsGrim commented on addons/medical_treatment/stringtable.xml
I'm not a fan of these setting titles.

2023-06-28 10:51 UTC, LinkIsGrim commented on addons/medical_treatment/stringtable.xml
> +            <English>Controls whether a patient's wounds must be bandaged or stitched in order to use a PAK.</English>
```suggestion
            <English>Controls whether a patient's wounds must be bandaged or stitched in order to use a Personal Aid Kit.</English>
```

2023-06-28 10:51 UTC, LinkIsGrim commented on addons/medical_treatment/stringtable.xml
> +            <English>Controls whether PAKs can be used on patients in pain.</English>
```suggestion
            <English>Controls whether Personal Aid Kits can be used on patients in pain.</English>
```

2023-06-28 10:51 UTC, LinkIsGrim commented on addons/medical_treatment/stringtable.xml
> +            <English>Controls whether PAKs can be used on patients with untreated fractures.</English>
```suggestion
            <English>Controls whether Personal Aid Kits can be used on patients with untreated fractures.</English>
```

2023-06-28 10:51 UTC, LinkIsGrim commented on addons/medical_treatment/stringtable.xml
> +            <English>Minimum blood volume percentage required to use a PAK.</English>
```suggestion
            <English>Minimum blood volume percentage required to use a Personal Aid Kit.</English>
```

2023-06-28 10:51 UTC, LinkIsGrim commented on addons/medical_treatment/stringtable.xml
> +            <English>Minimum heart rate required to use a PAK.</English>
```suggestion
            <English>Minimum heart rate required to use a Personal Aid Kit.</English>
```

2023-06-28 10:51 UTC, LinkIsGrim commented on addons/medical_status/functions/fnc_isInStableCondition.sqf
> +if (GET_BLOOD_VOLUME(_unit) < _requiredBloodVolume) exitWith {false};
This'd be more intuitive if it used qualitative blood loss (hemmorhage class, "Lost some/a lot of/etc blood") instead.

2023-06-28 10:51 UTC, LinkIsGrim commented on docs/wiki/feature/medical-system.md
> +Required Wounds State PAK: Controls whether a patient's wounds must be bandaged or stitched in order to use a PAK.
```suggestion
Required Wounds State PAK: Controls whether a patient's wounds must be bandaged or stitched in order to use a Personal Aid Kit.
```

2023-06-28 10:51 UTC, LinkIsGrim commented on docs/wiki/feature/medical-system.md
> +Allow Pain PAK: Controls whether PAKs can be used on patients in pain.
```suggestion
Allow Pain PAK: Controls whether Personal Aid Kits can be used on patients in pain.
```

2023-06-28 10:51 UTC, LinkIsGrim commented on docs/wiki/feature/medical-system.md
> +Min Blood PAK: Minimum blood volume percentage required to use a PAK.
```suggestion
Min Blood PAK: Minimum blood volume percentage required to use a Personal Aid Kit.
```

2023-06-28 10:51 UTC, LinkIsGrim commented on docs/wiki/feature/medical-system.md
> +Min Heart Rate PAK: Minimum heart rate required to use a PAK.
```suggestion
Min Heart Rate PAK: Minimum heart rate required to use a Personal Aid Kit.
```

2023-07-05 19:32 UTC, dgibso29 commented
Kindly, after nearly 3 years of trying to get this merged, it is no longer worth redeveloping this yet again versus maintaining an override in our framework.

2023-07-05 19:32 UTC, closed without merging