Vehicles - Add Resume/Set functionality to speed control
acemod/ACE3 pull request #8967
Opened 2022-07-15 22:00 UTC by Dystopian

**When merged this pull request will:**
- add `Set`/`Resume` functionality on `Speed-`/`Speed+` keys (like `SET-`/`RES+` buttons)
- make `Autothrottle` work for UAV planes
- fix `Autothrottle` not working for copilots
- fix speed control for UGV gunner
- disable speed control activating if engine is off
- disable speed control activating in UAV when map is opened
- disable CC activating if speed < 1 (stopped or moving backward)
- disable speed control when `Feature Camera` starts (`Zeus`, `Splendid Camera`, etc.)

`Speed Control` means `Cruise Control` and `Speed Limiter` here.

I don't know if it's worth touching setting strings. I would just add ` / Resume` to `<English>Increase Speed Limit</English>` line but not for other languages. Deleting them would be rude to translators. Commenting them out would be good but **tabler** sees commented lines as missing.

Looks like UGV are correctly driven by player as gunner. These are `Stomper` (`Car` child), ED-1D and ED-1E (`Tank` children). And speed control works correctly with gunner too now.

I also had idea to store `speedLimit` and `isCruiseControl` vars per vehicle but decided it's not worth it.

2023-05-16 07:51 UTC, BrettMayson requested changes
Tested, works good for me in SP

2023-05-16 07:51 UTC, BrettMayson commented on addons/vehicles/XEH_postInit.sqf
> +["ACE3 Vehicles", QGVAR(speedLimiter), localize LSTRING(SpeedLimiter),{
```suggestion
["ACE3 Vehicles", QGVAR(speedLimiter), localize LSTRING(SpeedLimiter), {
```

2023-05-16 07:51 UTC, BrettMayson commented on addons/vehicles/functions/fnc_autoThrottle.sqf
> +    if ("" != call CBA_fnc_getActiveFeatureCamera) then {
```suggestion
    if (call CBA_fnc_getActiveFeatureCamera != "") then {
```
I'm fine if this is ignored if others prefer it I guess, but this looks really weird to me

2023-05-16 07:51 UTC, BrettMayson commented on addons/vehicles/functions/fnc_speedLimiter.sqf
> +    if ("" != call CBA_fnc_getActiveFeatureCamera) then {
```suggestion
    if (call CBA_fnc_getActiveFeatureCamera != "") then {
```

2023-05-16 14:59 UTC, BrettMayson approved these changes

2023-06-28 13:44 UTC, LinkIsGrim approved these changes

2023-06-28 14:17 UTC, merged