Medical Treatment - Suture
acemod/ACE3 pull request #9020
Opened 2022-08-31 20:27 UTC by BrettMayson

**When merged this pull request will:**
- [x] Add logic for sutures
- [ ] A model and ui picture
 
I've have yet to make a model for Arma 3, not sure about the process. If anyone else wants to make one it would be greatly appreciated, otherwise it may be a bit before I get around to figuring it out

2022-08-31 22:09 UTC, Walthzer commented
For a sutures model, just a small package with one of them?
![Capture](https://user-images.githubusercontent.com/19926813/187793753-487d484c-92ed-44a8-aec7-c836d8e6a48d.PNG)

and/or a box that expands into packages when one gets used from it? 
![15824ET-3967902197](https://user-images.githubusercontent.com/19926813/187794122-5e53f494-bb2a-43e1-87b1-13df7c06eb04.jpg)

2022-09-01 21:05 UTC, Walthzer commented
Textures are a little iffy but how about these? 
![result](https://user-images.githubusercontent.com/19926813/188012772-98a562ac-932f-4562-b1c3-9445a87b6921.png)

2022-09-01 21:07 UTC, BrettMayson commented
Looks good to me, I'd pick a less aggressive color though

2022-09-01 21:13 UTC, kymckay commented
Would be good to colour match the green from the image above

2022-09-01 21:27 UTC, Walthzer commented
Does look better yeah, good call. Trying to figure out a good UI picture now.
![result](https://user-images.githubusercontent.com/19926813/188015012-e56e74c3-c0b4-4e12-a751-1f2ef36ff1e2.png)

2022-09-01 21:42 UTC, Walthzer commented
If I just take the model, this is the best it would be. Can't get legible text within a reasonable resolution. Otherwise I'd say we display it in the UI as thread with a needle? 
![result](https://user-images.githubusercontent.com/19926813/188018009-853c9edb-fb39-476d-b0b3-6c65be230c64.png)

2022-09-02 00:16 UTC, BrettMayson commented
I'd use a thread and needle yeah

2022-09-03 15:21 UTC, Walthzer commented
Tried some different designs and this is what looks the "best", fitting a suture into the UI is awkward :P. Currently think the "Suture" picture is the better one. 

![ui_pictures](https://user-images.githubusercontent.com/19926813/188277191-be29ab1b-f2e5-469c-9868-711f8cc0133a.png)

2022-09-04 02:43 UTC, Walthzer commented
Can't seems to create a PR onto your fork Brett. Probably doing something wrong. How would I go about "appending" to this PR from my end?

2022-09-04 02:52 UTC, PabstMirror commented
@Walthzer 
https://github.com/BrettMayson/ACE3/compare/consume_stitches...Walthzer:ACE3:consume_stitches
post a link to your pr back here if you make one because it won't show up on this repo

2022-09-04 03:08 UTC, Walthzer commented
Wierd, the GitHub Interface didn't allow me to select Brett from the dropdown, huh. But that link did the trick Pabst. Created a PR for Brett to add the models to the branch: [the PR](https://github.com/BrettMayson/ACE3/pull/2#issue-1361018455)

2022-09-06 16:27 UTC, BrettMayson commented
Anyone know what the issue here is?

2022-09-06 17:08 UTC, Walthzer commented
> Anyone know what the issue here is?

Sadly I do, I included the wrong models. They are trying to load textures files from the wrong path. Ugh. Will open a fix in a few.

2022-09-07 16:44 UTC, Walthzer commented
@BrettMayson Opened a [PR](https://github.com/BrettMayson/ACE3/pull/3) that *should* fix the paths.

2022-09-14 04:56 UTC, BrettMayson commented
Used this in an MP mission tonight, worked great and models are nice. Thanks @Walthzer for the contribution!

2022-10-10 08:55 UTC, BrettMayson commented
Probably going to want to reduce the mass of the surgical kit, forgot to mention on my last post that we set it to `10`. Seems to be good so far, but we could go slightly more.

2022-10-22 01:34 UTC, BrettMayson commented
We are getting `Cannot load texture z\wfar\addons\axe\data\suture_nohq.paa`

@Walthzer

2022-10-22 06:23 UTC, Walthzer commented
That issue was due to the wrong model being copied over. I just checked the code again I am quite sure I had fixed it. Where is the error from?

2023-02-21 14:19 UTC, veteran29 requested changes

2023-02-21 14:22 UTC, BrettMayson commented on addons/medical_treatment/functions/fnc_surgicalKitStart.sqf
> +    ([_medic, _patient, ["ACE_suture"]] call FUNC(useItem));
Have my medics been using free suture's without reporting it as a bug :|

2023-02-21 14:31 UTC, veteran29 approved these changes
LGTM

2023-02-24 05:26 UTC, PabstMirror commented on addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp
>          consumeItem = QGVAR(consumeSurgicalKit);
not sure if needed, but might help to add a little note about how it works (not like most bools)
```suggestion
        consumeItem = QGVAR(consumeSurgicalKit); // setting can be 0,1,2 - only 1 will consume items[]
```

2023-02-24 05:26 UTC, PabstMirror approved these changes

2023-03-06 20:17 UTC, merged