Arsenal - Add init/remove local events to Arsenal creation/destruction
acemod/ACE3 pull request #9064
Opened 2022-10-05 16:27 UTC by TACHarsis

**When merged this pull request will:**
* Add "ace_arsenal_boxInitialized" local event on the creation of an arsenal box via fnc_initBox
* Add "ace_arsenal_boxRemoved" local event on the removal of an arsenal box via fnc_removeBox

* Events are added to arsenal event list in docs

Why?: My mod adds sub actions to the arsenal interaction menu tree. Currently there is no way to cleanly hook into that process and add these extensions every time an arsenal is created. There is an event "initBox" that gets fired only in multiplayer and for global arsenals that works in certain cases, but feels like an abuse of an internal version. 
I see no point of rewriting that event, as it clearly serves a specific purpose, not a gneralized one.
A generalized *local* event to enable reactions to arsenals being initiated or removed is the better solution and almost free.

 ### IMPORTANT
 * [x]  If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
 * [x]  [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
 * [x]  Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2022-10-06 11:10 UTC, BrettMayson requested changes

2022-10-06 11:10 UTC, BrettMayson commented on addons/arsenal/functions/fnc_removeBox.sqf
> +} else {
```suggestion
} else {
```

2022-10-06 11:10 UTC, BrettMayson commented on addons/arsenal/functions/fnc_removeBox.sqf
> +    [QGVAR(onremoveBox), _object] call CBA_fnc_localEvent;
```suggestion
    [QGVAR(onRemoveBox), _object] call CBA_fnc_localEvent;
```

2022-10-06 13:31 UTC, BrettMayson requested changes

2022-10-06 13:31 UTC, BrettMayson commented on addons/arsenal/functions/fnc_initBox.sqf
> +        [QGVAR(boxInitialized), _object, _items] call CBA_fnc_localEvent;
```suggestion
        [QGVAR(boxInitialized), [_object, _items]] call CBA_fnc_localEvent;
```

2022-10-06 21:21 UTC, BrettMayson approved these changes

2022-10-20 02:41 UTC, PabstMirror approved these changes

2022-10-22 00:28 UTC, merged