WIP: Tagging - Add custom stencil text tags
acemod/ACE3 pull request #9149
Opened 2023-02-09 21:27 UTC by PabstMirror

Add stencil text tags
Using https://fonts.google.com/specimen/Saira+Stencil+One (Open Font License)

todo:
- [ ] not sure cause of `Warning Message: Cannot load mipmap z\ace\addons\fonts\sairastencilone\sairastencilone46-01.paa`

2023-03-05 23:56 UTC, PabstMirror commented
![23Cdrrn](https://user-images.githubusercontent.com/9376747/222993233-3e4acabc-6481-43a7-ba28-aecde38724bc.jpg)
```
Warning Message: Cannot load mipmap z\ace\addons\fonts\pixelsplitterbold\pixelsplitterbold46-01.paa
Extreme texture size (1x1)
Texture init failed.
```

But doing a dummy call to `"Test" getTextWidth ["ACE_Stencil", 0.3];` at preStart fixes
I'm pretty sure this is just an arma bug because it looks like all font textures should be preloaded

2023-04-30 21:33 UTC, jonpas commented
How does this work in combination with `novehicleclanlogo` being enabled?

2023-04-30 21:36 UTC, veteran29 approved these changes

2023-05-01 17:42 UTC, jonpas requested changes

2023-05-01 17:42 UTC, jonpas commented on addons/tagging/CfgEden.hpp
> +                        condition = "objectVehicle";
```suggestion
                        condition = "objectVehicle";
```

2023-05-01 17:42 UTC, jonpas commented on addons/tagging/functions/fnc_addStencilTag.sqf
> + * 2: Required Item <STRING> (default: ACE_SpraypaintBlack)
```suggestion
 * 2: Required Item <STRING> (default: "ACE_SpraypaintBlack")
```

2023-05-01 17:42 UTC, jonpas commented on addons/tagging/functions/fnc_addStencilTag.sqf
> + * 4: Background Color (in HEX 6 or 8) <STRING> (default: clear)
```suggestion
 * 4: Background Color (in HEX 6 or 8) <STRING> (default: "clear")
```

2023-05-01 17:42 UTC, jonpas commented on addons/tagging/functions/fnc_generateStencilTexture.sqf
> + * 3: Background Color (in HEX 6 or 8) <STRING> (default: clear)
```suggestion
 * 2: Text Color (in HEX 6 or 8) <STRING> (default: "black")
 * 3: Background Color (in HEX 6 or 8) <STRING> (default: "clear")
```

2023-05-01 17:51 UTC, PabstMirror commented on addons/tagging/functions/fnc_addStencilTag.sqf
> + * 4: Background Color (in HEX 6 or 8) <STRING> (default: clear)
```suggestion
 * 4: Background Color (in HEX 6 or 8) <STRING> (default: "00000000" - transparent)
```

2023-06-01 00:49 UTC, PabstMirror commented on addons/tagging/functions/fnc_generateStencilTexture.sqf
> + * 3: Background Color (in HEX 6 or 8) <STRING> (default: clear)
```suggestion
 * 2: Text Color (in HEX 6 or 8) <STRING> (default: black)
 * 3: Background Color (in HEX 6 or 8) <STRING> (default: "00000000" - transparent)
```

2023-06-01 00:50 UTC, PabstMirror commented on addons/tagging/functions/fnc_generateStencilTexture.sqf
> + * 2: Text Color (in HEX 6 or 8) <STRING> (default: black)
```suggestion
 * 2: Text Color (in HEX 6 or 8) <STRING> (default: "000000" - black)
```

2023-06-28 10:57 UTC, jonpas commented
> How does this work in combination with `novehicleclanlogo` being enabled?

Would still like to know that.

2023-07-23 22:16 UTC, LinkIsGrim commented
> > How does this work in combination with `novehicleclanlogo` being enabled?
> 
> Would still like to know that.

Stencil is removed on mission start.

2023-07-23 22:17 UTC, LinkIsGrim commented
Player interaction for this would be nice?

2023-07-23 22:27 UTC, jonpas approved these changes

2023-07-24 02:55 UTC, merged