Explosives - Add getVar to disable setShotParents
acemod/ACE3 pull request #9190
Opened 2023-04-30 22:19 UTC by PabstMirror

I don't think this needs an actual setting, setVar should be fine imho

2023-04-30 22:26 UTC, jonpas requested changes

2023-04-30 22:26 UTC, jonpas commented on docs/wiki/framework/explosives-framework.md
> +#### 5.4 Disabiling `setShotParents`.
Typo

2023-05-01 17:40 UTC, PabstMirror commented on docs/wiki/framework/explosives-framework.md
> +#### 5.4 Disabiling `setShotParents`.
```suggestion
#### 5.4 Disabling `setShotParents`.
```

2023-05-01 17:44 UTC, jonpas approved these changes

2023-05-03 16:55 UTC, merged