Improve: Create "ace_explosives_setup" CBA Event
acemod/ACE3 pull request #9197
Opened 2023-05-10 00:51 UTC by ThatArcanist

**When merged this pull request will:**
- Add an event to the "fnc_setupExplosive" for when an explosive is successfully placed down.

Currently, the "ace_explosives_place" event only triggers when a "trigger" is added to the explosive. This adds an event that passes in the placed explosive's vehicle, the mag class and the unit that placed the explosive.

Personally, the current event should be renamed and this one should be named "place" however, to avoid fallout with other mods that depend on this one, I've simply created a new one to keep the two separate and cause other mods to need to be updated.

2023-05-15 05:17 UTC, BrettMayson commented
I have added back the `IMPORTANT` section of the PR template that was removed. Please complete the 3 items in that section.

2023-05-15 08:58 UTC, ThatArcanist commented
@BrettMayson The event "ace_explosives_place" is undocumented, would you prefer I left this out of documentation or created a section for the two events in the explosives framework documentation

2023-05-15 16:10 UTC, BrettMayson commented
I would document `ace_explosives_place` if it is missing

2023-05-15 16:33 UTC, Drofseh commented
Title of this PR should be something like `Explosives - Add {changes}`

2023-06-20 11:32 UTC, LinkIsGrim requested changes

2023-06-20 12:16 UTC, BrettMayson commented on docs/wiki/framework/events-framework.md
> +|`ace_explosives_place` | [_explosiveVehicle, _magClassname, _unit] | Global | Listen | Explosive is armed
> Currently, the "ace_explosives_place" event only triggers when a "trigger" is added to the explosive. This adds an event that passes in the placed explosive's vehicle, the mag class and the unit that placed the explosive.

The names are not great, but that is to keep compatibility, they are not inverted.

2023-06-20 12:19 UTC, ThatArcanist commented on docs/wiki/framework/events-framework.md
> +|`ace_explosives_place` | [_explosiveVehicle, _magClassname, _unit] | Global | Listen | Explosive is armed
@BrettMayson I just updated it, The setup and place had the wrong event parameters

2023-06-20 12:21 UTC, BrettMayson commented on docs/wiki/framework/events-framework.md
> +|`ace_explosives_place` | [_explosiveVehicle, _magClassname, _unit] | Global | Listen | Explosive is armed
Yes, I missed that and was good to fix, base on Grim's latest comment on the PR I think he was confused about the naming though

2023-06-20 12:34 UTC, LinkIsGrim requested changes

2023-06-20 12:34 UTC, LinkIsGrim commented on docs/wiki/framework/events-framework.md
> +|`ace_explosives_setup` | [_explosiveVehicle, _magClassname, _unit] | Global | Listen | Explosive is placed in the world
```suggestion
|`ace_explosives_place` | [_explosive, _dir, _pitch, _unit] | Global | Listen | Explosive is placed in the world
|`ace_explosives_setup` | [_explosiveVehicle, _magClassname, _unit] | Global | Listen | Explosive is armed
```

2023-06-20 12:36 UTC, BrettMayson commented on docs/wiki/framework/events-framework.md
> +|`ace_explosives_setup` | [_explosiveVehicle, _magClassname, _unit] | Global | Listen | Explosive is placed in the world
> Currently, the "ace_explosives_place" event only triggers when a "trigger" is added to the explosive. This adds an event that passes in the placed explosive's vehicle, the mag class and the unit that placed the explosive.

2023-06-20 12:37 UTC, LinkIsGrim commented on docs/wiki/framework/events-framework.md
> +|`ace_explosives_setup` | [_explosiveVehicle, _magClassname, _unit] | Global | Listen | Explosive is placed in the world
Disregard.

2023-06-20 12:38 UTC, LinkIsGrim approved these changes

2023-06-20 19:36 UTC, merged