Arsenal - Add optional Tools category
acemod/ACE3 pull request #9247
Opened 2023-07-09 17:42 UTC by LinkIsGrim

**When merged this pull request will:**
- Add config property to sort items in CfgWeapons as tools.
- Add optional tools tab, controlled by setting.

Currently includes flashlights, Defusal Kit, clacklers, Notepad (no effect currently, as it is a magazine), Chemlight Shield, AtragMX, Kestrel, Fortify Tool, DAGR/MicroDAGR, Entrenching Tool, rangetables and range card, Wirecutters, SSWT kit, Spotting Scope, Mine Detector, Toolkit, Cellphone. Dead Man's Switch, HuntIR Monitor, and Map Tools.

![107410_20230709204108_1](https://github.com/acemod/ACE3/assets/69561145/afcaa7ee-d067-451b-ad74-5aea15824d40)

![107410_20230709204138_1](https://github.com/acemod/ACE3/assets/69561145/a949bb25-41a3-428c-bda5-947d60783a25)

### IMPORTANT

- [x] If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [x] [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- [x] Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2023-07-09 20:24 UTC, Dystopian reviewed
IMHO setting is not needed. Can't imagine situation when tools grouping can hurt.

2023-07-09 20:24 UTC, Dystopian commented on addons/arsenal/stringtable.xml
> +            <English>Shows the tools tab in the left panel, containing items like toolkits, mine detectors, flashlights, etc.\nItems sorted to the Tools tab won't be shown in Misc. Items.</English>
```suggestion
            <English>Shows the tools tab in the right panel, containing items like toolkits, mine detectors, flashlights, etc.\nItems sorted to the Tools tab won't be shown in Misc. Items.</English>
```

2023-07-10 03:52 UTC, PabstMirror commented on addons/arsenal/stringtable.xml
> +            <English>Tools</English>
```suggestion                          
            <English>Tools</English>
            <Czech>Nástroje</Czech>
            <German>Werkzeuge</German>
            <Russian>Инструменты</Russian>
            <Polish>Narzędzia</Polish>
            <Italian>Strumenti</Italian>
            <Spanish>Herramientas</Spanish>
            <French>Outils</French>
            <Chinese>工具</Chinese>
            <Japanese>ツール</Japanese>
            <Korean>도구</Korean>
            <Portuguese>Ferramentas</Portuguese>
            <Chinesesimp>工具</Chinesesimp>
            <Turkish>Araçlar</Turkish>
```

2023-07-10 04:01 UTC, LinkIsGrim commented
> IMHO setting is not needed. Can't imagine situation when tools grouping can hurt.

People mad about their stuff not being in the usual place? I agree though.

2023-07-10 18:32 UTC, LinkIsGrim commented
Is there anything else that should be sorted to Tools?

2023-07-11 03:58 UTC, rautamiekka requested changes
Grammar/spelling fixes.

2023-07-11 03:58 UTC, rautamiekka commented on addons/arsenal/functions/fnc_addRightPanelButton.sqf
> + * 4: Move button if its position is overriden <BOOL> (default: false)
```suggestion
 * 4: Move button if its position is overridden <BOOL> (default: false)
```

2023-07-11 03:58 UTC, rautamiekka commented on addons/arsenal/functions/fnc_addRightPanelButton.sqf
> +params [["_items", [], [[]]], ["_tooltip", "", [""]], ["_picture", QPATHTOF(data\iconCustom.paa), [""]], ["_override", -1, [0]], ["_keepIfOverriden", false, [false]]];
```suggestion
params [["_items", [], [[]]], ["_tooltip", "", [""]], ["_picture", QPATHTOF(data\iconCustom.paa), [""]], ["_override", -1, [0]], ["_keepIfOverridden", false, [false]]];
```

2023-07-11 03:58 UTC, rautamiekka commented on addons/arsenal/functions/fnc_addRightPanelButton.sqf
> +    GVAR(customRightPanelButtons) set [_position, [_items apply {toLower _x}, _picture, _tooltip, _keepIfOverriden]];
```suggestion
    GVAR(customRightPanelButtons) set [_position, [_items apply {toLower _x}, _picture, _tooltip, _keepIfOverridden]];
```

2023-07-11 03:58 UTC, rautamiekka commented on docs/wiki/framework/arsenal-framework.md
> +ACE Medical Treatment and ACE Field Rations also have their own custom sub categories:
```suggestion
ACE Medical Treatment and ACE Field Rations also have their own custom subcategories:
```

2023-07-11 03:58 UTC, rautamiekka commented on docs/wiki/framework/arsenal-framework.md
> +4  | Keep button if overriden | Bool | Optional (default: `false`)
```suggestion
4  | Keep button if overridden | Bool | Optional (default: `false`)
```

2023-07-11 03:58 UTC, rautamiekka commented on docs/wiki/framework/arsenal-framework.md
> +Only items that are listed under 'Misc. Items' or other sub categories are available for sub categories.
```suggestion
Only items that are listed under 'Misc. Items' or other sub-categories are available for subcategories.
```

2023-07-11 03:58 UTC, rautamiekka commented on docs/wiki/framework/arsenal-framework.md
> +If the 'Keep button if overriden' argument is used, the button will be moved to the bottom of the rest if its position is overriden.
```suggestion
If the 'Keep button if overriden' argument is used, the button will be moved to the bottom of the rest if its position is overridden.
```

2023-07-21 18:58 UTC, PabstMirror approved these changes

2023-07-21 19:01 UTC, johnb432 reviewed
What happens/is supposed to happen if all custom panels are taken, all of them having `_moveOnOverwrite` enabled, and you add another panel with `_override != -1`?

Is the existing panel overwritten or is the panel rejected?

2023-07-21 19:05 UTC, johnb432 commented on docs/wiki/framework/arsenal-framework.md
> +If the 'Move button on overwrite' argument is used, the button will be moved to the bottom of the rest if its position is overriden.
Looks like one of corrections you made earlier was reverted: `overriden` -> `overridden`

2023-07-21 19:11 UTC, LinkIsGrim commented
> What happens/is supposed to happen if all custom panels are taken, all of them having `_moveOnOverwrite` enabled, and you add another panel with `_override != -1`?
> 
> Is the existing panel overwritten or is the panel rejected?

Existing panel is overwritten. Override wins.

2023-07-21 19:39 UTC, merged