WIP - Medical GUI - Show selected body part on body image
acemod/ACE3 pull request #9471
Opened 2023-10-08 20:50 UTC by amsteadrayle

**When merged this pull request will:**
- Indicate the selected body part in the body image display

### IMPORTANT

- [ ] If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [x] [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- [x] Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2023-10-08 20:50 UTC, amsteadrayle commented
Demo video:
https://www.youtube.com/watch?v=Az0f1CMXNuY

The red overlay is just temporary for demo and testing. New textures need to be made, but the functionality should be complete.

From my comment in the feature request issue:

> Add an outline to the currently selected body part. This makes it abundantly clear which body part you have selected, and also adds feedback when clicking a body part to indicate that you _have_ selected that body part.

2023-10-08 22:59 UTC, amsteadrayle commented
First pass at body part outlines:

https://github.com/acemod/ACE3/assets/2516219/50365b43-5329-4747-a1d6-841552e6a5ae

2023-10-09 02:59 UTC, amsteadrayle commented
https://github.com/acemod/ACE3/assets/2516219/0901c4c2-aac1-4cd4-9b65-90e67fe73d1d

2023-10-09 17:01 UTC, LinkIsGrim commented on addons/medical_gui/stringtable.xml
> +            <English>Body part outline color</English>
```suggestion
            <English>Body Part Outline Color</English>
```

2023-10-10 23:39 UTC, LinkIsGrim requested changes
Fix merge conflicts

2023-10-10 23:39 UTC, LinkIsGrim commented on addons/medical_gui/initSettings.sqf
> +    [LSTRING(BodypartOutlineColor_DisplayName),LSTRING(BodypartOutlineColor_Description)],
```suggestion
    QGVAR(bodyPartOutlineColor),
    "COLOR",
    [LSTRING(bodyPartOutlineColor_DisplayName), LSTRING(bodyPartOutlineColor_Description)],
```

2023-10-10 23:39 UTC, LinkIsGrim commented on addons/medical_gui/stringtable.xml
> +        <Key ID="STR_ACE_Medical_GUI_BodypartOutlineColor_Description">
```suggestion
        <Key ID="STR_ACE_Medical_GUI_bodyPartOutlineColor_DisplayName">
            <English>Body Part Outline Color</English>
        </Key>
        <Key ID="STR_ACE_Medical_GUI_bodyPartOutlineColor_Description">
```

2023-10-11 06:10 UTC, PabstMirror approved these changes

2023-10-11 09:21 UTC, LinkIsGrim approved these changes

2023-10-11 09:25 UTC, merged