Translations - Add Polish Translations
acemod/ACE3 pull request #9489
Opened 2023-10-14 21:50 UTC by Krzyciu

**When merged this pull request will:**
- Add missing polish translations
- Remove russian translation from polish - ace_common

### IMPORTANT

- [ ] If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [x] [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- [x] Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2023-10-14 22:00 UTC, PabstMirror commented on addons/fieldmanual/stringtable.xml
> +</Polish>
```suggestion
            </Polish>
```

2023-10-14 22:00 UTC, PabstMirror commented on addons/fieldmanual/stringtable.xml
> +</Polish>
```suggestion
            </Polish>
```

2023-10-14 22:01 UTC, PabstMirror commented on addons/fieldmanual/stringtable.xml
> +Przetłumaczono z www.DeepL.com/Translator (wersja darmowa)</Polish>
not sure about the url?
```suggestion
Przetłumaczono z www.DeepL.com/Translator (wersja darmowa)
            </Polish>
```

2023-10-14 22:02 UTC, PabstMirror commented on addons/fieldmanual/stringtable.xml
> +</Polish>
oh wait, these should be on the same line

2023-10-14 22:04 UTC, PabstMirror commented on addons/fieldmanual/stringtable.xml
> +Przetłumaczono z www.DeepL.com/Translator (wersja darmowa)</Polish>
```suggestion
            <Polish>%3Liny%4 mają wiele zastosowań, takich jak %3Holowanie%4 pojazdów czy %3Zjeżdżanie na Linach%4 z helikopterów.&lt;br/&gt;&lt;br/&gt;%3Holowanie:%4&lt;br/&gt;%2Podejdź pod pojazd.&lt;br/&gt;%2Użyj [%3%13%4] i wybierz %3Holowanie%4.&lt;br/&gt;%2Wybierz długość liny. &lt;br/&gt;%2Wybierz punkt zaczepu liny na holującym pojeździe.&lt;br/&gt;%2Wybierz punkt zaczepu liny na holowanym pojeździe.&lt;br/&gt;&lt;br/&gt;%3Dostępne Długości Liny:%4&lt;br/&gt;%2 3.2 metera&lt;br/&gt;%2 6.2 metera&lt;br/&gt;%2 12.2 metera&lt;br/&gt;%2 15.2 metera&lt;br/&gt;%2 18.3 metera&lt;br/&gt;%2 27.4 metera&lt;br/&gt;%2 36.6 metera Przetłumaczono z www.DeepL.com/Translator (wersja darmowa)</Polish>
```
not sure about the url at end?

2023-10-14 22:04 UTC, PabstMirror commented on addons/fieldmanual/stringtable.xml
> +            <Polish>Budowanie  Fortyfikacji</Polish>
```suggestion
            <Polish>Budowanie Fortyfikacji</Polish>
```

2023-10-14 22:04 UTC, PabstMirror commented on addons/fieldmanual/stringtable.xml
> +</Polish>
```suggestion
            <Polish>%3Czuwak%4 jest urządzeniem pozwalającym wysadzić %3Ładunek Wybuchowy%4 gdy żołnierz zginie.&lt;br/&gt;&lt;br/&gt;%3Użycie:%4&lt;br/&gt;%2Użyj [%3%12%4] i wybierz %3Mat. Wybuchowe%4.&lt;br/&gt;%2Wybierz %3Czuwak%4 i połącz wybrany %3Ładunek Wybuchowy%4.&lt;br/&gt;%2W celu odłączenia powtórz czynności i wybierz odłącz.</Polish>
```

2023-10-15 00:59 UTC, PabstMirror commented on addons/fieldmanual/stringtable.xml
> +</Polish>
```suggestion
            <Polish>%3DAGR%4 jest uproszczoną wersją%3MicroDAGR GPS%4. Posiada podobne funkcje, ale brakuje mu map dostępnych w %3MicroDAGR GPS%4.&lt;br/&gt;&lt;br/&gt;%3Użycie:%4&lt;br/&gt;%2Wyekwipuj %3DAGR%4.&lt;br/&gt;%2Użyj [%3%12%4] i wybierz %3Konfiguruj%4 lub %3Przełącz%4.&lt;br/&gt;&lt;br/&gt;Poniższe menu są dostępne podczas konfiguracji %3DAGR:%4&lt;br/&gt;%11%2Widok Danych: WIP&lt;br/&gt;%11%2GoTo WP: Wybierz waypoint do śledzenia.&lt;br/&gt;%11%2WP List: Dodaj/Edytuj/Usuń waypointy.&lt;br/&gt;%11%2Połącz do: Połącz %3DAGR%4 do dalmierza %3Vector 21%4.&lt;br/&gt;%11%2Opcje</Polish>
```

2023-10-16 00:27 UTC, veteran29 requested changes

2023-10-16 00:27 UTC, veteran29 commented on addons/fieldmanual/stringtable.xml
> +            <Polish>%3Horus ATragMX%4 uwzględnia warunki atmosferyczne, dane broni, amunicję, zasięg, prędkość wylotową do wyliczenia precyzyjnych nastaw - ponadto uwzględnia %3Efekt Coriolisa%4 oraz
```suggestion
            <Polish>%3Horus ATragMX%4 uwzględnia warunki atmosferyczne, dane broni, amunicję, zasięg, prędkość wylotową do wyliczenia precyzyjnych nastaw - ponadto uwzględnia %3Efekt Coriolisa%4 oraz %3Efekt Spinowy%4. %3ATragMX%4, załadowany na komputer przenośny wyprodukowany przez %3TDS Recon%4, jest łatwy i prosty w użyciu. %3Recon%4 spełnia rygorystyczne wymagania %3MIL-STD-810F%4 pod względem odporności na upadek, wibracje, wilgotność, wyskość oraz ekstremalne temperatury.&lt;br/&gt;&lt;br/&gt;%3Użycie:%4&lt;br/&gt;Wejdź na wiki po więcej informacji.</Polish>
```

2023-10-16 00:27 UTC, veteran29 commented on addons/fieldmanual/stringtable.xml
> +            <Polish>Niższa Temperatura twoje Broni</Polish>
```suggestion
            <Polish>Niższa Temperatura twojej Broni</Polish>
```

2023-10-16 00:27 UTC, veteran29 commented on addons/fieldmanual/stringtable.xml
> +            <Polish>Zablokuj/Odbloku Pojazdy</Polish>
```suggestion
            <Polish>Zablokuj/Odblokuj Pojazdy</Polish>
```

2023-10-16 00:28 UTC, veteran29 approved these changes

2023-10-16 05:21 UTC, merged