Common - Add function to check if action with modifier being pressed
acemod/ACE3 pull request #9594
Opened 2023-10-27 06:09 UTC by PabstMirror

ref https://community.bistudio.com/wiki/actionKeysEx

e.g. "teamSwitch" key is (ctrl + U)
actionKeys "TeamSwitch" = [4.87784e+008]
won't match the input from keyDown EH

not sure if there is an easier way?
`addUserActionEventHandler` wasn't firing on the display

2023-10-27 09:26 UTC, johnb432 commented
I was working on something to add keycombo support some time ago which include support for double tap keys, I'll bring it up to date and post it.

2023-10-28 15:32 UTC, rautamiekka requested changes

2023-10-28 15:32 UTC, rautamiekka commented on addons/common/functions/fnc_actionKeyPressed.sqf
> +        && {_mainDevice == "KEYBOARD"}
```suggestion
        && _mainDevice isEqualTo "KEYBOARD"
```
If the correct casing is always returns.

And surely the lazy eval doesn't save anything with such a cheap check.

2023-10-28 15:32 UTC, rautamiekka commented on addons/common/functions/fnc_actionKeyPressed.sqf
> +            (!_shift) && {!_ctrl} && {!_alt}
And surely the lazy eval doesn't save anything with such a cheap check.
```suggestion
            !_shift && !_ctrl && !_alt
```

2023-10-28 15:32 UTC, rautamiekka commented on addons/common/functions/fnc_actionKeyPressed.sqf
> +            (_comboDevice == "KEYBOARD")
```suggestion
            (_comboDevice isEqualTo "KEYBOARD")
```
If the correct casing is always returned.

2023-10-28 15:32 UTC, rautamiekka commented on addons/common/functions/fnc_actionKeyPressed.sqf
> +        && {!_isDoubleTap}
```suggestion
        && !_isDoubleTap
```
And surely the lazy eval doesn't save anything with such a cheap check.

2023-10-29 11:51 UTC, johnb432 commented
@PabstMirror I brought my old version up to date.

https://github.com/acemod/ACE3/blob/086b8821d37efc78bf34142142e5a324cc826502/addons/common/functions/fnc_disableUserInput.sqf

It can handle close to all if not all possible keycombos. I have tested various keybinds and actions, but not all.
The downside of my suggested version is that it can't handle the Escape key, as the `KeyUp` EH does not trigger for the Escape key (at least it doesn't in my tests).
I tried to make my suggestion more modular, as in make a different function with separate EH. However, that did not work, as, despite adding the `KeyDown` EH later in `FUNC(disableUserInput)`, the EH added in the different function did not trigger.

---
I also did several drive-by changes, such as taking 3DEN context into the button texts and replacing the string-codes with `toString` and code.

2024-01-07 18:32 UTC, johnb432 commented
Closed in favor of #9659, can be reopened if necessary.

2024-01-07 18:32 UTC, johnb432 commented
Closed in favor of #9659, can be reopened if necessary.

2024-01-07 18:32 UTC, closed without merging