Translations - Complete Italian + almost complete German translation
acemod/ACE3 pull request #9673
Opened 2023-12-08 16:55 UTC by mrschick

**When merged this pull request will:**
- Add all missing Italian translations;
- Add all missing German translations except for `addon/fieldmanual`;
- Review and overhaul all Italian translations;

2023-12-09 06:55 UTC, bux commented
This PR is huge ...

2023-12-09 08:46 UTC, BaerMitUmlaut requested changes

2023-12-09 08:46 UTC, BaerMitUmlaut commented on addons/arsenal/stringtable.xml
> +            <German>Suche\nSTRG + Click für live-aktualisierung während man schreibt</German>
Großschreibung, ich würde auch "während des Schreibens" bevorzugen

2023-12-10 03:20 UTC, PabstMirror approved these changes

2023-12-10 23:44 UTC, PabstMirror approved these changes

2023-12-10 23:50 UTC, PabstMirror commented
@mrschick
I can fix the merge conflicts if you give write access to PR

2023-12-11 00:12 UTC, mrschick commented
Unfortunately [not possible on organization PRs](https://github.com/orgs/community/discussions/5634) ATM, will try to resolve them on my end.

2023-12-11 00:14 UTC, PabstMirror commented
https://github.com/acemod/ACE3/tree/pr/9673-mergeconflicts has fixes if you can merge that

2023-12-11 00:22 UTC, mrschick commented
Ah, just committed the resolution through GitHub's frontend. I guess it takes a bit to display.

2023-12-12 01:31 UTC, merged