Keybind for put or take out earplugs
acemod/ACE3 pull request #9804
Opened 2024-02-26 11:49 UTC by prisonerMO

**When merged this pull request will:**
- This request will add keybind for put or take out earplug
- Default ALT+H
- Addon Controls -> ACE Equipment

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-02-26 14:07 UTC, jonpas commented
What is the benefit in a keybind?

2024-02-26 14:11 UTC, veteran29 commented
IMO should be unassigned by default.

2024-02-26 15:19 UTC, prisonerMO commented
> IMO should be unassigned by default.

Yeah.
That would be better.

2024-02-26 15:48 UTC, johnb432 commented
> What is the benefit in a keybind?

Like some other keybinds in ACE: It's more convenient and faster than going through the menu. Adding the possibility to bind a key to toggle earplugs doesn't impact the game in a negative way, imo, especially if it's left unbound by default.

2024-02-26 19:30 UTC, johnb432 requested changes
Good for a first PR!

2024-02-26 19:30 UTC, johnb432 commented on addons/hearing/XEH_postInit.sqf
>  if (!hasInterface) exitWith {};
Don't need to register keybinds on machines that don't have interfaces.
```suggestion
if (!hasInterface) exitWith {};

#include "initKeybinds.inc.sqf"
```

2024-02-26 19:30 UTC, johnb432 commented on addons/hearing/initKeybinds.inc.sqf
> +[35, [false, false, true]], true] call CBA_fnc_addKeybind; //(ALT + H)
Removed default keybind, added new line at the end of the file and changed some code formatting, as well as some functions:
```suggestion
["ACE3 Equipment", QGVAR(putOrRemoveEarplugs), LLSTRING(PutOrRemoveEarplugs), {
    // Conditions: specific
    if !([ACE_player, objNull, ["isNotSwimming", "isNotInside", "isNotSitting"]] call EFUNC(common,canInteractWith)) exitWith {false};

    if (GVAR(EnableCombatDeafness) && {!([ACE_player] call FUNC(hasEarPlugsIn))} && {[ACE_player, "ACE_EarPlugs"] call EFUNC(common,hasItem)}) exitWith {
        [ACE_player, true] call FUNC(putInEarPlugs);
        true
    };
    if (GVAR(EnableCombatDeafness) && {[ACE_player] call FUNC(hasEarPlugsIn)}) exitWith {
        [ACE_player, true] call FUNC(removeEarPlugs);
        true
    };
    
    false
}] call CBA_fnc_addKeybind; // UNBOUND

```

2024-02-26 19:30 UTC, johnb432 commented on addons/hearing/stringtable.xml
> +            <English>Puts/takes out earplugs</English>
Other components do it this way:
```suggestion
            <English>Put/take out earplugs</English>
```

2024-02-26 19:40 UTC, prisonerMO commented
> Good for a first PR!

Thanks!
Thank you very much for clarifying how it should be done/what is done elsewhere and for correcting the code

2024-02-27 20:21 UTC, johnb432 approved these changes

2024-02-28 19:33 UTC, PabstMirror approved these changes

2024-02-28 19:41 UTC, LinkIsGrim approved these changes

2024-02-28 19:44 UTC, merged