Parachute - Add Seconds Indicator to Altimeter Watch
acemod/ACE3 pull request #9834
Opened 2024-03-07 13:13 UTC by mrschick

**When merged this pull request will:**
- Add `seconds` to the digital clock on the Altimeter Watch, changing its format to `HH:MM:SS`. Making it more useful for timing explosives or tracking artillery TOF accurately;

2024-03-07 15:34 UTC, BrettMayson approved these changes

2024-03-07 21:44 UTC, LinkIsGrim approved these changes

2024-03-09 09:14 UTC, johnb432 requested changes
![20240309101332_1](https://github.com/acemod/ACE3/assets/58661205/73c03adb-83ef-4b71-8881-1f340d7faf9a)
The right most digit's shadow is cut off.

2024-03-09 13:03 UTC, mrschick commented
Odd, I centered it more so that wouldn't happen and it looked ok, must have done something wrong then.

2024-03-09 13:24 UTC, mrschick commented
Looks different on my end 🤔
![20240309142325_1](https://github.com/acemod/ACE3/assets/58027418/4b3d81ce-fe54-4b41-8992-ba7422430f95)

2024-03-09 23:19 UTC, PabstMirror commented
![watch](https://github.com/acemod/ACE3/assets/9376747/55940392-29c7-4461-a40d-86bd2151f4e4)
Also a tiny bit cutoff for me
Probably no harm in just making the text rsc a bit wider if it's left aligned?

2024-03-09 23:37 UTC, mrschick commented
> Also a tiny bit cutoff for me

It seems like it's drawing the entire rsc more to the right for both of you.

> Probably no harm in just making the text rsc a bit wider if it's left aligned?

Done, looks fine to me again, though you should probably double check.

2024-03-10 09:55 UTC, johnb432 approved these changes

2024-03-10 11:10 UTC, mrschick commented
@johnb432 how did you get that debug window on the left of your screen?

2024-03-10 11:18 UTC, johnb432 commented
> @johnb432 how did you get that debug window on the left of your screen?

[Advanced Developer Tools](https://steamcommunity.com/sharedfiles/filedetails/?id=2369477168)

2024-03-10 14:48 UTC, merged