Ace keybinds
acemod/ACE3 pull request #9842
Opened 2024-03-09 15:17 UTC by prisonerMO

**When merged this pull request will:**
- removes register keybinds on machines that don't have interfaces.

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-03-09 17:14 UTC, LinkIsGrim requested changes

2024-03-09 17:14 UTC, LinkIsGrim commented on addons/rangecard/XEH_postInit.sqf
> +#include "initKeybinds.inc.sqf"
```suggestion
#include "initKeybinds.inc.sqf"

```
newline at EOF

2024-03-09 17:14 UTC, LinkIsGrim commented on addons/mk6mortar/XEH_preInit.sqf
> -#include "initKeybinds.inc.sqf"
Not readded anywhere

2024-03-09 19:58 UTC, mharis001 commented
Is this needed?

https://github.com/CBATeam/CBA_A3/blob/master/addons/keybinding/fnc_addKeybind.sqf#L84

2024-03-10 14:58 UTC, LinkIsGrim approved these changes
Not particularly needed, but doesn't hurt.

2024-03-12 21:32 UTC, johnb432 approved these changes

2024-03-12 21:33 UTC, merged