Grenades - Improve multiple aspects
acemod/ACE3 pull request #9979
Opened 2024-04-27 15:50 UTC by johnb432

**When merged this pull request will:**
- `common`'s `FUNC(addToInventory)` was altered so that when you convert explosives, you don't have to drop them in order for you to use them. This change can be reverted once the bug in question (https://feedback.bistudio.com/T74244) has been addressed.
- Prevent pain from flashbangs if unit is invulnerable.
- Added 3 more sounds to flashbang detonations.
- Incendiary grenades now can damage multiple vehicles, instead of being limited to one.
- Contains #9978.
- Code cleanup.

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-04-28 01:11 UTC, rautamiekka requested changes

2024-04-28 01:11 UTC, rautamiekka commented on addons/grenades/functions/fnc_flashbangExplosionEH.sqf
> +          // Not used interally but could be useful for other mods
```suggestion
          // Not used internally but could be useful for other mods
```

2024-04-28 01:11 UTC, rautamiekka commented on addons/grenades/functions/fnc_incendiary.sqf
> +        if (local _x && {[_center, side group _x] call BIS_fnc_sideIsEnemy}) then { // WE WANT THE OBJECTS SIDE HERE!
```suggestion
        if (local _x && {[_center, side group _x] call BIS_fnc_sideIsEnemy}) then { // WE WANT THE OBJECT'S SIDE HERE!
```

2024-04-28 01:11 UTC, rautamiekka commented on addons/grenades/functions/fnc_incendiary.sqf
> +} forEach (_position nearObjects ALERT_NEAR_ENEMY_RANGE); // replace with nearEntities in 2.18
```suggestion
} forEach (_position nearObjects ALERT_NEAR_ENEMY_RANGE); //@todo replace with nearEntities in 2.18
```

2024-05-23 18:24 UTC, johnb432 commented on addons/grenades/functions/fnc_flashbangExplosionEH.sqf
> + * 0: FlashBang position ASL <ARRAY>
```suggestion
 * 0: Flashbang position ASL <ARRAY>
```

2024-05-23 18:28 UTC, johnb432 commented on addons/grenades/functions/fnc_incendiary.sqf
> +            {GETVAR(_x,EGVAR(cookoff,enableAmmoCookoff),EGVAR(cookoff,enableAmmobox))}
```suggestion
            {_x getVariable [QEGVAR(cookoff,enableAmmoCookoff), EGVAR(cookoff,enableAmmobox)]}
```

2024-06-18 08:05 UTC, merged